//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vssoft.Data.ERP.Dictionary
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIC_NHACUNGCAP
    {
        public int ID { get; set; }
        public string MaNhaCungCap { get; set; }
        public string TenNhaCungCap { get; set; }
        public string DienThoai { get; set; }
        public string DiaChi { get; set; }
        public string NguoiDaiDien { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
