//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vssoft.Data.ERP.Dictionary
{

    public class DIC_TINH
    {
        
        public DIC_TINH()
        {
        }
        public string MaTinh { get; set; }
        public string TenTinh { get; set; }
        public int Status { get; set; }
    }
}
