//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vssoft.ERP.ERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIC_BENHVIEN
    {
        public int ID { get; set; }
        public string MaBenhVien { get; set; }
        public string MaTinh { get; set; }
        public string MaHuyen { get; set; }
        public string MaChuQuan { get; set; }
        public string TenBenhVien { get; set; }
        public string TuyenBenhVien { get; set; }
        public int HangBenhVien { get; set; }
        public string DiaChi { get; set; }
        public int Status { get; set; }
        public bool Connect { get; set; }
    
    }
}
