//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vssoft.ERP.ERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIC_XAPHUONG
    {
        public string MaXa { get; set; }
        public string MaHuyen { get; set; }
        public string TenXa { get; set; }
    
        public virtual DIC_HUYEN DIC_HUYEN { get; set; }
    }
}
