//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vssoft.ERP.ERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIC_HUYEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DIC_HUYEN()
        {
            this.DIC_BENHVIEN = new HashSet<DIC_BENHVIEN>();
            this.DIC_XAPHUONG = new HashSet<DIC_XAPHUONG>();
        }
    
        public string MaHuyen { get; set; }
        public string MaTinh { get; set; }
        public string TenHuyen { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DIC_BENHVIEN> DIC_BENHVIEN { get; set; }
        public virtual DIC_TINH DIC_TINH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DIC_XAPHUONG> DIC_XAPHUONG { get; set; }
    }
}
