//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vssoft.ERP.ERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIC_NGHENGHIEP
    {
        public int ID { get; set; }
        public string MaNgheNghiep { get; set; }
        public string TenNgheNghiep { get; set; }
        public string MoTa { get; set; }
    }
}
