//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vssoft.ERP.ERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIC_DTBN
    {
        public byte IDDTBN { get; set; }
        public string TenDTBN { get; set; }
        public string MoTa { get; set; }
        public byte HinhThucThanhToan { get; set; }
        public int Status { get; set; }
        
    }
}
