namespace Vssoft.Common.Report
{
    using DevExpress.LookAndFeel;
    using DevExpress.Utils;
    using DevExpress.XtraBars;
    using DevExpress.XtraBars.Docking;
    using DevExpress.XtraEditors.Controls;
    using DevExpress.XtraEditors.Repository;
    using DevExpress.XtraReports.UserDesigner;
    using System;
    using System.ComponentModel;
    using System.Drawing;
    using System.Windows.Forms;
    using XtraReportsDemos;

    public class CustomDesignForm : XRDesignFormExBase
    {
        private BarDockControl barDockControlBottom;
        private BarDockControl barDockControlLeft;
        private BarDockControl barDockControlRight;
        private BarDockControl barDockControlTop;
        private BarDockPanelsListItem barDockPanelsListItem1;
        private BarEditItem barEditItem1;
        private BarEditItem barEditItem2;
        private BarReportTabButtonsListItem barReportTabButtonsListItem1;
        private BarStaticItem barStaticItem1;
        private BarSubItem barSubItem1;
        private BarSubItem barSubItem10;
        private BarSubItem barSubItem11;
        private BarSubItem barSubItem12;
        private BarSubItem barSubItem13;
        private BarSubItem barSubItem14;
        private BarSubItem barSubItem2;
        private BarSubItem barSubItem3;
        private BarSubItem barSubItem4;
        private BarSubItem barSubItem5;
        private BarSubItem barSubItem6;
        private BarSubItem barSubItem7;
        private BarSubItem barSubItem8;
        private BarSubItem barSubItem9;
        private BarSubItem bsiLookAndFeel;
        private CommandBarItem commandBarItem1;
        private CommandBarItem commandBarItem10;
        private CommandBarItem commandBarItem11;
        private CommandBarItem commandBarItem12;
        private CommandBarItem commandBarItem13;
        private CommandBarItem commandBarItem14;
        private CommandBarItem commandBarItem15;
        private CommandBarItem commandBarItem16;
        private CommandBarItem commandBarItem17;
        private CommandBarItem commandBarItem18;
        private CommandBarItem commandBarItem19;
        private CommandBarItem commandBarItem2;
        private CommandBarItem commandBarItem20;
        private CommandBarItem commandBarItem21;
        private CommandBarItem commandBarItem22;
        private CommandBarItem commandBarItem23;
        private CommandBarItem commandBarItem24;
        private CommandBarItem commandBarItem25;
        private CommandBarItem commandBarItem26;
        private CommandBarItem commandBarItem27;
        private CommandBarItem commandBarItem28;
        private CommandBarItem commandBarItem29;
        private CommandBarItem commandBarItem3;
        private CommandBarItem commandBarItem30;
        private CommandBarItem commandBarItem31;
        private CommandBarItem commandBarItem32;
        private CommandBarItem commandBarItem33;
        private CommandBarItem commandBarItem34;
        private CommandBarItem commandBarItem35;
        private CommandBarItem commandBarItem36;
        private CommandBarItem commandBarItem37;
        private CommandBarItem commandBarItem38;
        private CommandBarItem commandBarItem39;
        private CommandBarItem commandBarItem4;
        private CommandBarItem commandBarItem40;
        private CommandBarItem commandBarItem41;
        private CommandBarItem commandBarItem42;
        private CommandBarItem commandBarItem43;
        private CommandBarItem commandBarItem44;
        private CommandBarItem commandBarItem45;
        private CommandBarItem commandBarItem5;
        private CommandBarItem commandBarItem6;
        private CommandBarItem commandBarItem7;
        private CommandBarItem commandBarItem8;
        private CommandBarItem commandBarItem9;
        private CommandColorBarItem commandColorBarItem1;
        private CommandColorBarItem commandColorBarItem2;
        private Container components = null;
        private DesignBar designBar1;
        private DesignBar designBar2;
        private DesignBar designBar3;
        private DesignBar designBar4;
        private DesignBar designBar5;
        private DesignBar designBar6;
        private DesignRepositoryItemComboBox designRepositoryItemComboBox1;
        private FieldListDockPanel fieldListDockPanel1;
        private DesignControlContainer fieldListDockPanel1_Container;
        private GroupAndSortDockPanel groupAndSortDockPanel1;
        private DesignControlContainer groupAndSortDockPanel1_Container;
        private DockPanel panelContainer1;
        private DockPanel panelContainer2;
        private PropertyGridDockPanel propertyGridDockPanel1;
        private DesignControlContainer propertyGridDockPanel1_Container;
        private ReportExplorerDockPanel reportExplorerDockPanel1;
        private DesignControlContainer reportExplorerDockPanel1_Container;
        private RecentlyUsedItemsComboBox ricbFontName;
        private RepositoryItemComboBox ricbFontSize;
        private ToolBoxDockPanel toolBoxDockPanel1;
        private DesignControlContainer toolBoxDockPanel1_Container;
        private XRBarToolbarsListItem xrBarToolbarsListItem1;
        private XRDesignBarManager xrDesignBarManager1;
        private XRDesignDockManager xrDesignDockManager1;
        private XRZoomBarEditItem xrZoomBarEditItem1;

        public CustomDesignForm()
        {
            this.InitializeComponent();
            BarItem item = new BarLookAndFeelListItem(UserLookAndFeel.Default);
            this.xrDesignBarManager1.Items.Add(item);
            this.bsiLookAndFeel.AddItem(item);
        }

        private void CustomDesignForm_Load(object sender, EventArgs e)
        {
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing && (this.components != null))
            {
                this.components.Dispose();
            }
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            ComponentResourceManager manager = new ComponentResourceManager(typeof(CustomDesignForm));
            this.xrDesignBarManager1 = new XRDesignBarManager();
            this.designBar1 = new DesignBar();
            this.barSubItem1 = new BarSubItem();
            this.commandBarItem31 = new CommandBarItem();
            this.commandBarItem39 = new CommandBarItem();
            this.commandBarItem32 = new CommandBarItem();
            this.commandBarItem33 = new CommandBarItem();
            this.commandBarItem40 = new CommandBarItem();
            this.commandBarItem41 = new CommandBarItem();
            this.barSubItem2 = new BarSubItem();
            this.commandBarItem37 = new CommandBarItem();
            this.commandBarItem38 = new CommandBarItem();
            this.commandBarItem34 = new CommandBarItem();
            this.commandBarItem35 = new CommandBarItem();
            this.commandBarItem36 = new CommandBarItem();
            this.commandBarItem42 = new CommandBarItem();
            this.commandBarItem43 = new CommandBarItem();
            this.barSubItem3 = new BarSubItem();
            this.barReportTabButtonsListItem1 = new BarReportTabButtonsListItem();
            this.barSubItem4 = new BarSubItem();
            this.xrBarToolbarsListItem1 = new XRBarToolbarsListItem();
            this.barSubItem5 = new BarSubItem();
            this.barDockPanelsListItem1 = new BarDockPanelsListItem();
            this.barSubItem6 = new BarSubItem();
            this.commandColorBarItem1 = new CommandColorBarItem();
            this.commandColorBarItem2 = new CommandColorBarItem();
            this.barSubItem7 = new BarSubItem();
            this.commandBarItem1 = new CommandBarItem();
            this.commandBarItem2 = new CommandBarItem();
            this.commandBarItem3 = new CommandBarItem();
            this.barSubItem8 = new BarSubItem();
            this.commandBarItem4 = new CommandBarItem();
            this.commandBarItem5 = new CommandBarItem();
            this.commandBarItem6 = new CommandBarItem();
            this.commandBarItem7 = new CommandBarItem();
            this.barSubItem9 = new BarSubItem();
            this.commandBarItem9 = new CommandBarItem();
            this.commandBarItem10 = new CommandBarItem();
            this.commandBarItem11 = new CommandBarItem();
            this.commandBarItem12 = new CommandBarItem();
            this.commandBarItem13 = new CommandBarItem();
            this.commandBarItem14 = new CommandBarItem();
            this.commandBarItem8 = new CommandBarItem();
            this.barSubItem10 = new BarSubItem();
            this.commandBarItem15 = new CommandBarItem();
            this.commandBarItem16 = new CommandBarItem();
            this.commandBarItem17 = new CommandBarItem();
            this.commandBarItem18 = new CommandBarItem();
            this.barSubItem11 = new BarSubItem();
            this.commandBarItem19 = new CommandBarItem();
            this.commandBarItem20 = new CommandBarItem();
            this.commandBarItem21 = new CommandBarItem();
            this.commandBarItem22 = new CommandBarItem();
            this.barSubItem12 = new BarSubItem();
            this.commandBarItem23 = new CommandBarItem();
            this.commandBarItem24 = new CommandBarItem();
            this.commandBarItem25 = new CommandBarItem();
            this.commandBarItem26 = new CommandBarItem();
            this.barSubItem13 = new BarSubItem();
            this.commandBarItem27 = new CommandBarItem();
            this.commandBarItem28 = new CommandBarItem();
            this.barSubItem14 = new BarSubItem();
            this.commandBarItem29 = new CommandBarItem();
            this.commandBarItem30 = new CommandBarItem();
            this.bsiLookAndFeel = new BarSubItem();
            this.designBar2 = new DesignBar();
            this.designBar3 = new DesignBar();
            this.barEditItem1 = new BarEditItem();
            this.ricbFontName = new RecentlyUsedItemsComboBox();
            this.barEditItem2 = new BarEditItem();
            this.ricbFontSize = new RepositoryItemComboBox();
            this.designBar4 = new DesignBar();
            this.designBar5 = new DesignBar();
            this.barStaticItem1 = new BarStaticItem();
            this.designBar6 = new DesignBar();
            this.commandBarItem44 = new CommandBarItem();
            this.xrZoomBarEditItem1 = new XRZoomBarEditItem();
            this.designRepositoryItemComboBox1 = new DesignRepositoryItemComboBox();
            this.commandBarItem45 = new CommandBarItem();
            this.barDockControlTop = new BarDockControl();
            this.barDockControlBottom = new BarDockControl();
            this.barDockControlLeft = new BarDockControl();
            this.barDockControlRight = new BarDockControl();
            this.xrDesignDockManager1 = new XRDesignDockManager();
            this.panelContainer1 = new DockPanel();
            this.panelContainer2 = new DockPanel();
            this.reportExplorerDockPanel1 = new ReportExplorerDockPanel();
            this.reportExplorerDockPanel1_Container = new DesignControlContainer();
            this.fieldListDockPanel1 = new FieldListDockPanel();
            this.fieldListDockPanel1_Container = new DesignControlContainer();
            this.propertyGridDockPanel1 = new PropertyGridDockPanel();
            this.propertyGridDockPanel1_Container = new DesignControlContainer();
            this.toolBoxDockPanel1 = new ToolBoxDockPanel();
            this.toolBoxDockPanel1_Container = new DesignControlContainer();
            this.groupAndSortDockPanel1 = new GroupAndSortDockPanel();
            this.groupAndSortDockPanel1_Container = new DesignControlContainer();
            base.xrDesignPanel.BeginInit();
            this.xrDesignBarManager1.BeginInit();
            this.ricbFontName.BeginInit();
            this.ricbFontSize.BeginInit();
            this.designRepositoryItemComboBox1.BeginInit();
            this.xrDesignDockManager1.BeginInit();
            this.panelContainer1.SuspendLayout();
            this.panelContainer2.SuspendLayout();
            this.reportExplorerDockPanel1.SuspendLayout();
            this.fieldListDockPanel1.SuspendLayout();
            this.propertyGridDockPanel1.SuspendLayout();
            this.toolBoxDockPanel1.SuspendLayout();
            this.groupAndSortDockPanel1.SuspendLayout();
            base.SuspendLayout();
            base.xrDesignPanel.Location = new Point(200, 0x4e);
            base.xrDesignPanel.ShowComponentTray = false;
            base.xrDesignPanel.Size = new Size(0x1b0, 0x109);
            this.xrDesignBarManager1.Bars.AddRange(new Bar[] { this.designBar1, this.designBar2, this.designBar3, this.designBar4, this.designBar5, this.designBar6 });
            this.xrDesignBarManager1.DockControls.Add(this.barDockControlTop);
            this.xrDesignBarManager1.DockControls.Add(this.barDockControlBottom);
            this.xrDesignBarManager1.DockControls.Add(this.barDockControlLeft);
            this.xrDesignBarManager1.DockControls.Add(this.barDockControlRight);
            this.xrDesignBarManager1.DockManager = this.xrDesignDockManager1;
            this.xrDesignBarManager1.FontNameBox = this.ricbFontName;
            this.xrDesignBarManager1.FontNameEdit = this.barEditItem1;
            this.xrDesignBarManager1.FontSizeBox = this.ricbFontSize;
            this.xrDesignBarManager1.FontSizeEdit = this.barEditItem2;
            this.xrDesignBarManager1.Form = this;
            this.xrDesignBarManager1.FormattingToolbar = this.designBar3;
            this.xrDesignBarManager1.HintStaticItem = this.barStaticItem1;
            this.xrDesignBarManager1.ImageStream = (ImageCollectionStreamer) manager.GetObject("xrDesignBarManager1.ImageStream");
            this.xrDesignBarManager1.Items.AddRange(new BarItem[] { 
                this.barEditItem1, this.barEditItem2, this.commandBarItem1, this.commandBarItem2, this.commandBarItem3, this.commandColorBarItem1, this.commandColorBarItem2, this.commandBarItem4, this.commandBarItem5, this.commandBarItem6, this.commandBarItem7, this.commandBarItem8, this.commandBarItem9, this.commandBarItem10, this.commandBarItem11, this.commandBarItem12,
                this.commandBarItem13, this.commandBarItem14, this.commandBarItem15, this.commandBarItem16, this.commandBarItem17, this.commandBarItem18, this.commandBarItem19, this.commandBarItem20, this.commandBarItem21, this.commandBarItem22, this.commandBarItem23, this.commandBarItem24, this.commandBarItem25, this.commandBarItem26, this.commandBarItem27, this.commandBarItem28,
                this.commandBarItem29, this.commandBarItem30, this.commandBarItem31, this.commandBarItem32, this.commandBarItem33, this.commandBarItem34, this.commandBarItem35, this.commandBarItem36, this.commandBarItem37, this.commandBarItem38, this.barStaticItem1, this.barSubItem1, this.barSubItem2, this.barSubItem3, this.barReportTabButtonsListItem1, this.barSubItem4,
                this.xrBarToolbarsListItem1, this.barSubItem5, this.barDockPanelsListItem1, this.barSubItem6, this.barSubItem7, this.barSubItem8, this.barSubItem9, this.barSubItem10, this.barSubItem11, this.barSubItem12, this.barSubItem13, this.barSubItem14, this.commandBarItem39, this.commandBarItem40, this.commandBarItem41, this.commandBarItem42,
                this.commandBarItem43, this.bsiLookAndFeel, this.commandBarItem44, this.commandBarItem45
            });
            this.xrDesignBarManager1.LayoutToolbar = this.designBar4;
            this.xrDesignBarManager1.MainMenu = this.designBar1;
            this.xrDesignBarManager1.MaxItemId = 0x45;
            this.xrDesignBarManager1.RepositoryItems.AddRange(new RepositoryItem[] { this.ricbFontName, this.ricbFontSize, this.designRepositoryItemComboBox1 });
            this.xrDesignBarManager1.StatusBar = this.designBar5;
            this.xrDesignBarManager1.Toolbar = this.designBar2;
            this.xrDesignBarManager1.XRDesignPanel = base.xrDesignPanel;
            this.xrDesignBarManager1.ZoomItem = this.xrZoomBarEditItem1;
            this.designBar1.BarName = "MainMenu";
            this.designBar1.DockCol = 0;
            this.designBar1.DockRow = 0;
            this.designBar1.DockStyle = BarDockStyle.Top;
            this.designBar1.LinksPersistInfo.AddRange(new LinkPersistInfo[] { new LinkPersistInfo(this.barSubItem1), new LinkPersistInfo(this.barSubItem2), new LinkPersistInfo(this.barSubItem3), new LinkPersistInfo(this.barSubItem6), new LinkPersistInfo(this.bsiLookAndFeel) });
            this.designBar1.OptionsBar.MultiLine = true;
            this.designBar1.OptionsBar.UseWholeRow = true;
            this.designBar1.Text = "Main Menu";
            this.barSubItem1.Caption = "&File";
            this.barSubItem1.Id = 0x2b;
            this.barSubItem1.LinksPersistInfo.AddRange(new LinkPersistInfo[] { new LinkPersistInfo(this.commandBarItem31), new LinkPersistInfo(this.commandBarItem39), new LinkPersistInfo(this.commandBarItem32), new LinkPersistInfo(this.commandBarItem33, true), new LinkPersistInfo(this.commandBarItem40), new LinkPersistInfo(this.commandBarItem41, true) });
            this.barSubItem1.Name = "barSubItem1";
            this.commandBarItem31.Caption = "&New";
            this.commandBarItem31.Command = ReportCommand.NewReport;
            this.commandBarItem31.Hint = "Create a new blank report";
            this.commandBarItem31.Id = 0x22;
            this.commandBarItem31.ImageIndex = 9;
            this.commandBarItem31.ItemShortcut = new BarShortcut(Keys.Control | Keys.N);
            this.commandBarItem31.Name = "commandBarItem31";
            this.commandBarItem39.Caption = "New with &Wizard...";
            this.commandBarItem39.Command = ReportCommand.NewReportWizard;
            this.commandBarItem39.Hint = "Create a new report using the Wizard";
            this.commandBarItem39.Id = 60;
            this.commandBarItem39.ItemShortcut = new BarShortcut(Keys.Control | Keys.W);
            this.commandBarItem39.Name = "commandBarItem39";
            this.commandBarItem32.Caption = "&Open...";
            this.commandBarItem32.Command = ReportCommand.OpenFile;
            this.commandBarItem32.Hint = "Open a report";
            this.commandBarItem32.Id = 0x23;
            this.commandBarItem32.ImageIndex = 10;
            this.commandBarItem32.ItemShortcut = new BarShortcut(Keys.Control | Keys.O);
            this.commandBarItem32.Name = "commandBarItem32";
            this.commandBarItem33.Caption = "&Save";
            this.commandBarItem33.Command = ReportCommand.SaveFile;
            this.commandBarItem33.Enabled = false;
            this.commandBarItem33.Hint = "Save a report";
            this.commandBarItem33.Id = 0x24;
            this.commandBarItem33.ImageIndex = 11;
            this.commandBarItem33.ItemShortcut = new BarShortcut(Keys.Control | Keys.S);
            this.commandBarItem33.Name = "commandBarItem33";
            this.commandBarItem40.Caption = "Save &As...";
            this.commandBarItem40.Command = ReportCommand.SaveFileAs;
            this.commandBarItem40.Enabled = false;
            this.commandBarItem40.Hint = "Save a report with a new name";
            this.commandBarItem40.Id = 0x3d;
            this.commandBarItem40.Name = "commandBarItem40";
            this.commandBarItem41.Caption = "Back to the Reports Main Demo";
            this.commandBarItem41.Command = ReportCommand.Exit;
            this.commandBarItem41.Hint = "Close the designer";
            this.commandBarItem41.Id = 0x3e;
            this.commandBarItem41.Name = "commandBarItem41";
            this.barSubItem2.Caption = "&Edit";
            this.barSubItem2.Id = 0x2c;
            this.barSubItem2.LinksPersistInfo.AddRange(new LinkPersistInfo[] { new LinkPersistInfo(this.commandBarItem37, true), new LinkPersistInfo(this.commandBarItem38), new LinkPersistInfo(this.commandBarItem34, true), new LinkPersistInfo(this.commandBarItem35), new LinkPersistInfo(this.commandBarItem36), new LinkPersistInfo(this.commandBarItem42), new LinkPersistInfo(this.commandBarItem43, true) });
            this.barSubItem2.Name = "barSubItem2";
            this.commandBarItem37.Caption = "&Undo";
            this.commandBarItem37.Command = ReportCommand.Undo;
            this.commandBarItem37.Enabled = false;
            this.commandBarItem37.Hint = "Undo the last operation";
            this.commandBarItem37.Id = 40;
            this.commandBarItem37.ImageIndex = 15;
            this.commandBarItem37.ItemShortcut = new BarShortcut(Keys.Control | Keys.Z);
            this.commandBarItem37.Name = "commandBarItem37";
            this.commandBarItem38.Caption = "&Redo";
            this.commandBarItem38.Command = ReportCommand.Redo;
            this.commandBarItem38.Enabled = false;
            this.commandBarItem38.Hint = "Redo the last operation";
            this.commandBarItem38.Id = 0x29;
            this.commandBarItem38.ImageIndex = 0x10;
            this.commandBarItem38.ItemShortcut = new BarShortcut(Keys.Control | Keys.Y);
            this.commandBarItem38.Name = "commandBarItem38";
            this.commandBarItem34.Caption = "Cu&t";
            this.commandBarItem34.Command = ReportCommand.Cut;
            this.commandBarItem34.Enabled = false;
            this.commandBarItem34.Hint = "Delete the control and copy it to the clipboard";
            this.commandBarItem34.Id = 0x25;
            this.commandBarItem34.ImageIndex = 12;
            this.commandBarItem34.ItemShortcut = new BarShortcut(Keys.Control | Keys.X);
            this.commandBarItem34.Name = "commandBarItem34";
            this.commandBarItem35.Caption = "&Copy";
            this.commandBarItem35.Command = ReportCommand.Copy;
            this.commandBarItem35.Enabled = false;
            this.commandBarItem35.Hint = "Copy the control to the clipboard";
            this.commandBarItem35.Id = 0x26;
            this.commandBarItem35.ImageIndex = 13;
            this.commandBarItem35.ItemShortcut = new BarShortcut(Keys.Control | Keys.C);
            this.commandBarItem35.Name = "commandBarItem35";
            this.commandBarItem36.Caption = "&Paste";
            this.commandBarItem36.Command = ReportCommand.Paste;
            this.commandBarItem36.Enabled = false;
            this.commandBarItem36.Hint = "Add the control from the clipboard";
            this.commandBarItem36.Id = 0x27;
            this.commandBarItem36.ImageIndex = 14;
            this.commandBarItem36.ItemShortcut = new BarShortcut(Keys.Control | Keys.V);
            this.commandBarItem36.Name = "commandBarItem36";
            this.commandBarItem42.Caption = "&Delete";
            this.commandBarItem42.Command = ReportCommand.Delete;
            this.commandBarItem42.Enabled = false;
            this.commandBarItem42.Hint = "Delete the control";
            this.commandBarItem42.Id = 0x3f;
            this.commandBarItem42.Name = "commandBarItem42";
            this.commandBarItem43.Caption = "Select &All";
            this.commandBarItem43.Command = ReportCommand.SelectAll;
            this.commandBarItem43.Enabled = false;
            this.commandBarItem43.Hint = "Select all the controls in the document";
            this.commandBarItem43.Id = 0x40;
            this.commandBarItem43.ItemShortcut = new BarShortcut(Keys.Control | Keys.A);
            this.commandBarItem43.Name = "commandBarItem43";
            this.barSubItem3.Caption = "&View";
            this.barSubItem3.Id = 0x2d;
            this.barSubItem3.LinksPersistInfo.AddRange(new LinkPersistInfo[] { new LinkPersistInfo(this.barReportTabButtonsListItem1), new LinkPersistInfo(this.barSubItem4, true), new LinkPersistInfo(this.barSubItem5, true) });
            this.barSubItem3.Name = "barSubItem3";
            this.barReportTabButtonsListItem1.Caption = "Tab Buttons";
            this.barReportTabButtonsListItem1.Id = 0x2e;
            this.barReportTabButtonsListItem1.Name = "barReportTabButtonsListItem1";
            this.barSubItem4.Caption = "&Toolbars";
            this.barSubItem4.Id = 0x2f;
            this.barSubItem4.LinksPersistInfo.AddRange(new LinkPersistInfo[] { new LinkPersistInfo(this.xrBarToolbarsListItem1) });
            this.barSubItem4.Name = "barSubItem4";
            this.xrBarToolbarsListItem1.Caption = "&Toolbars";
            this.xrBarToolbarsListItem1.Id = 0x30;
            this.xrBarToolbarsListItem1.Name = "xrBarToolbarsListItem1";
            this.barSubItem5.Caption = "&Windows";
            this.barSubItem5.Id = 0x31;
            this.barSubItem5.LinksPersistInfo.AddRange(new LinkPersistInfo[] { new LinkPersistInfo(this.barDockPanelsListItem1) });
            this.barSubItem5.Name = "barSubItem5";
            this.barDockPanelsListItem1.Caption = "&Windows";
            this.barDockPanelsListItem1.Id = 50;
            this.barDockPanelsListItem1.Name = "barDockPanelsListItem1";
            this.barDockPanelsListItem1.ShowCustomizationItem = false;
            this.barDockPanelsListItem1.ShowDockPanels = true;
            this.barDockPanelsListItem1.ShowToolbars = false;
            this.barSubItem6.Caption = "Fo&rmat";
            this.barSubItem6.Id = 0x33;
            this.barSubItem6.LinksPersistInfo.AddRange(new LinkPersistInfo[] { new LinkPersistInfo(this.commandColorBarItem1), new LinkPersistInfo(this.commandColorBarItem2), new LinkPersistInfo(this.barSubItem7, true), new LinkPersistInfo(this.barSubItem8), new LinkPersistInfo(this.barSubItem9, true), new LinkPersistInfo(this.barSubItem10), new LinkPersistInfo(this.barSubItem11, true), new LinkPersistInfo(this.barSubItem12), new LinkPersistInfo(this.barSubItem13, true), new LinkPersistInfo(this.barSubItem14, true) });
            this.barSubItem6.Name = "barSubItem6";
            this.commandColorBarItem1.ButtonStyle = BarButtonStyle.DropDown;
            this.commandColorBarItem1.Caption = "For&eground Color";
            this.commandColorBarItem1.Command = ReportCommand.ForeColor;
            this.commandColorBarItem1.Enabled = false;
            this.commandColorBarItem1.Glyph = (Image) manager.GetObject("commandColorBarItem1.Glyph");
            this.commandColorBarItem1.Hint = "Set the foreground color of the control";
            this.commandColorBarItem1.Id = 5;
            this.commandColorBarItem1.Name = "commandColorBarItem1";
            this.commandColorBarItem2.ButtonStyle = BarButtonStyle.DropDown;
            this.commandColorBarItem2.Caption = "Bac&kground Color";
            this.commandColorBarItem2.Command = ReportCommand.BackColor;
            this.commandColorBarItem2.Enabled = false;
            this.commandColorBarItem2.Glyph = (Image) manager.GetObject("commandColorBarItem2.Glyph");
            this.commandColorBarItem2.Hint = "Set the background color of the control";
            this.commandColorBarItem2.Id = 6;
            this.commandColorBarItem2.Name = "commandColorBarItem2";
            this.barSubItem7.Caption = "&Font";
            this.barSubItem7.Id = 0x34;
            this.barSubItem7.LinksPersistInfo.AddRange(new LinkPersistInfo[] { new LinkPersistInfo(this.commandBarItem1, true), new LinkPersistInfo(this.commandBarItem2), new LinkPersistInfo(this.commandBarItem3) });
            this.barSubItem7.Name = "barSubItem7";
            this.commandBarItem1.Caption = "&Bold";
            this.commandBarItem1.Command = ReportCommand.FontBold;
            this.commandBarItem1.Enabled = false;
            this.commandBarItem1.Hint = "Make the font bold";
            this.commandBarItem1.Id = 2;
            this.commandBarItem1.ImageIndex = 0;
            this.commandBarItem1.ItemShortcut = new BarShortcut(Keys.Control | Keys.B);
            this.commandBarItem1.Name = "commandBarItem1";
            this.commandBarItem2.Caption = "&Italic";
            this.commandBarItem2.Command = ReportCommand.FontItalic;
            this.commandBarItem2.Enabled = false;
            this.commandBarItem2.Hint = "Make the font italic";
            this.commandBarItem2.Id = 3;
            this.commandBarItem2.ImageIndex = 1;
            this.commandBarItem2.ItemShortcut = new BarShortcut(Keys.Control | Keys.I);
            this.commandBarItem2.Name = "commandBarItem2";
            this.commandBarItem3.Caption = "&Underline";
            this.commandBarItem3.Command = ReportCommand.FontUnderline;
            this.commandBarItem3.Enabled = false;
            this.commandBarItem3.Hint = "Underline the font";
            this.commandBarItem3.Id = 4;
            this.commandBarItem3.ImageIndex = 2;
            this.commandBarItem3.ItemShortcut = new BarShortcut(Keys.Control | Keys.U);
            this.commandBarItem3.Name = "commandBarItem3";
            this.barSubItem8.Caption = "&Justify";
            this.barSubItem8.Id = 0x35;
            this.barSubItem8.LinksPersistInfo.AddRange(new LinkPersistInfo[] { new LinkPersistInfo(this.commandBarItem4, true), new LinkPersistInfo(this.commandBarItem5), new LinkPersistInfo(this.commandBarItem6), new LinkPersistInfo(this.commandBarItem7) });
            this.barSubItem8.Name = "barSubItem8";
            this.commandBarItem4.Caption = "&Left";
            this.commandBarItem4.Command = ReportCommand.JustifyLeft;
            this.commandBarItem4.Enabled = false;
            this.commandBarItem4.Hint = "Align the control’s text to the left";
            this.commandBarItem4.Id = 7;
            this.commandBarItem4.ImageIndex = 5;
            this.commandBarItem4.Name = "commandBarItem4";
            this.commandBarItem5.Caption = "&Center";
            this.commandBarItem5.Command = ReportCommand.JustifyCenter;
            this.commandBarItem5.Enabled = false;
            this.commandBarItem5.Hint = "Align the control’s text to the center";
            this.commandBarItem5.Id = 8;
            this.commandBarItem5.ImageIndex = 6;
            this.commandBarItem5.Name = "commandBarItem5";
            this.commandBarItem6.Caption = "&Right";
            this.commandBarItem6.Command = ReportCommand.JustifyRight;
            this.commandBarItem6.Enabled = false;
            this.commandBarItem6.Hint = "Align the control’s text to the right";
            this.commandBarItem6.Id = 9;
            this.commandBarItem6.ImageIndex = 7;
            this.commandBarItem6.Name = "commandBarItem6";
            this.commandBarItem7.Caption = "&Justify";
            this.commandBarItem7.Command = ReportCommand.JustifyJustify;
            this.commandBarItem7.Enabled = false;
            this.commandBarItem7.Hint = "Justify the control’s text";
            this.commandBarItem7.Id = 10;
            this.commandBarItem7.ImageIndex = 8;
            this.commandBarItem7.Name = "commandBarItem7";
            this.barSubItem9.Caption = "&Align";
            this.barSubItem9.Id = 0x36;
            this.barSubItem9.LinksPersistInfo.AddRange(new LinkPersistInfo[] { new LinkPersistInfo(this.commandBarItem9, true), new LinkPersistInfo(this.commandBarItem10), new LinkPersistInfo(this.commandBarItem11), new LinkPersistInfo(this.commandBarItem12, true), new LinkPersistInfo(this.commandBarItem13), new LinkPersistInfo(this.commandBarItem14), new LinkPersistInfo(this.commandBarItem8, true) });
            this.barSubItem9.Name = "barSubItem9";
            this.commandBarItem9.Caption = "&Lefts";
            this.commandBarItem9.Command = ReportCommand.AlignLeft;
            this.commandBarItem9.Enabled = false;
            this.commandBarItem9.Hint = "Left align the selected controls";
            this.commandBarItem9.Id = 12;
            this.commandBarItem9.ImageIndex = 0x12;
            this.commandBarItem9.Name = "commandBarItem9";
            this.commandBarItem10.Caption = "&Centers";
            this.commandBarItem10.Command = ReportCommand.AlignVerticalCenters;
            this.commandBarItem10.Enabled = false;
            this.commandBarItem10.Hint = "Align the centers of the selected controls vertically";
            this.commandBarItem10.Id = 13;
            this.commandBarItem10.ImageIndex = 0x13;
            this.commandBarItem10.Name = "commandBarItem10";
            this.commandBarItem11.Caption = "&Rights";
            this.commandBarItem11.Command = ReportCommand.AlignRight;
            this.commandBarItem11.Enabled = false;
            this.commandBarItem11.Hint = "Right align the selected controls";
            this.commandBarItem11.Id = 14;
            this.commandBarItem11.ImageIndex = 20;
            this.commandBarItem11.Name = "commandBarItem11";
            this.commandBarItem12.Caption = "&Tops";
            this.commandBarItem12.Command = ReportCommand.AlignTop;
            this.commandBarItem12.Enabled = false;
            this.commandBarItem12.Hint = "Align the tops of the selected controls";
            this.commandBarItem12.Id = 15;
            this.commandBarItem12.ImageIndex = 0x15;
            this.commandBarItem12.Name = "commandBarItem12";
            this.commandBarItem13.Caption = "&Middles";
            this.commandBarItem13.Command = ReportCommand.AlignHorizontalCenters;
            this.commandBarItem13.Enabled = false;
            this.commandBarItem13.Hint = "Align the centers of the selected controls horizontally";
            this.commandBarItem13.Id = 0x10;
            this.commandBarItem13.ImageIndex = 0x16;
            this.commandBarItem13.Name = "commandBarItem13";
            this.commandBarItem14.Caption = "&Bottoms";
            this.commandBarItem14.Command = ReportCommand.AlignBottom;
            this.commandBarItem14.Enabled = false;
            this.commandBarItem14.Hint = "Align the bottoms of the selected controls";
            this.commandBarItem14.Id = 0x11;
            this.commandBarItem14.ImageIndex = 0x17;
            this.commandBarItem14.Name = "commandBarItem14";
            this.commandBarItem8.Caption = "to &Grid";
            this.commandBarItem8.Command = ReportCommand.AlignToGrid;
            this.commandBarItem8.Enabled = false;
            this.commandBarItem8.Hint = "Align the positions of the selected controls to the grid";
            this.commandBarItem8.Id = 11;
            this.commandBarItem8.ImageIndex = 0x11;
            this.commandBarItem8.Name = "commandBarItem8";
            this.barSubItem10.Caption = "&Make Same Size";
            this.barSubItem10.Id = 0x37;
            this.barSubItem10.LinksPersistInfo.AddRange(new LinkPersistInfo[] { new LinkPersistInfo(this.commandBarItem15, true), new LinkPersistInfo(this.commandBarItem16), new LinkPersistInfo(this.commandBarItem17), new LinkPersistInfo(this.commandBarItem18) });
            this.barSubItem10.Name = "barSubItem10";
            this.commandBarItem15.Caption = "&Width";
            this.commandBarItem15.Command = ReportCommand.SizeToControlWidth;
            this.commandBarItem15.Enabled = false;
            this.commandBarItem15.Hint = "Make the selected controls have the same width";
            this.commandBarItem15.Id = 0x12;
            this.commandBarItem15.ImageIndex = 0x18;
            this.commandBarItem15.Name = "commandBarItem15";
            this.commandBarItem16.Caption = "Size to Gri&d";
            this.commandBarItem16.Command = ReportCommand.SizeToGrid;
            this.commandBarItem16.Enabled = false;
            this.commandBarItem16.Hint = "Size the selected controls to the grid";
            this.commandBarItem16.Id = 0x13;
            this.commandBarItem16.ImageIndex = 0x19;
            this.commandBarItem16.Name = "commandBarItem16";
            this.commandBarItem17.Caption = "&Height";
            this.commandBarItem17.Command = ReportCommand.SizeToControlHeight;
            this.commandBarItem17.Enabled = false;
            this.commandBarItem17.Hint = "Make the selected controls have the same height";
            this.commandBarItem17.Id = 20;
            this.commandBarItem17.ImageIndex = 0x1a;
            this.commandBarItem17.Name = "commandBarItem17";
            this.commandBarItem18.Caption = "&Both";
            this.commandBarItem18.Command = ReportCommand.SizeToControl;
            this.commandBarItem18.Enabled = false;
            this.commandBarItem18.Hint = "Make the selected controls the same size";
            this.commandBarItem18.Id = 0x15;
            this.commandBarItem18.ImageIndex = 0x1b;
            this.commandBarItem18.Name = "commandBarItem18";
            this.barSubItem11.Caption = "&Horizontal Spacing";
            this.barSubItem11.Id = 0x38;
            this.barSubItem11.LinksPersistInfo.AddRange(new LinkPersistInfo[] { new LinkPersistInfo(this.commandBarItem19, true), new LinkPersistInfo(this.commandBarItem20), new LinkPersistInfo(this.commandBarItem21), new LinkPersistInfo(this.commandBarItem22) });
            this.barSubItem11.Name = "barSubItem11";
            this.commandBarItem19.Caption = "Make &Equal";
            this.commandBarItem19.Command = ReportCommand.HorizSpaceMakeEqual;
            this.commandBarItem19.Enabled = false;
            this.commandBarItem19.Hint = "Make the spacing between the selected controls equal";
            this.commandBarItem19.Id = 0x16;
            this.commandBarItem19.ImageIndex = 0x1c;
            this.commandBarItem19.Name = "commandBarItem19";
            this.commandBarItem20.Caption = "&Increase";
            this.commandBarItem20.Command = ReportCommand.HorizSpaceIncrease;
            this.commandBarItem20.Enabled = false;
            this.commandBarItem20.Hint = "Increase the spacing between the selected controls";
            this.commandBarItem20.Id = 0x17;
            this.commandBarItem20.ImageIndex = 0x1d;
            this.commandBarItem20.Name = "commandBarItem20";
            this.commandBarItem21.Caption = "&Decrease";
            this.commandBarItem21.Command = ReportCommand.HorizSpaceDecrease;
            this.commandBarItem21.Enabled = false;
            this.commandBarItem21.Hint = "Decrease the spacing between the selected controls";
            this.commandBarItem21.Id = 0x18;
            this.commandBarItem21.ImageIndex = 30;
            this.commandBarItem21.Name = "commandBarItem21";
            this.commandBarItem22.Caption = "&Remove";
            this.commandBarItem22.Command = ReportCommand.HorizSpaceConcatenate;
            this.commandBarItem22.Enabled = false;
            this.commandBarItem22.Hint = "Remove the spacing between the selected controls";
            this.commandBarItem22.Id = 0x19;
            this.commandBarItem22.ImageIndex = 0x1f;
            this.commandBarItem22.Name = "commandBarItem22";
            this.barSubItem12.Caption = "&Vertical Spacing";
            this.barSubItem12.Id = 0x39;
            this.barSubItem12.LinksPersistInfo.AddRange(new LinkPersistInfo[] { new LinkPersistInfo(this.commandBarItem23, true), new LinkPersistInfo(this.commandBarItem24), new LinkPersistInfo(this.commandBarItem25), new LinkPersistInfo(this.commandBarItem26) });
            this.barSubItem12.Name = "barSubItem12";
            this.commandBarItem23.Caption = "Make &Equal";
            this.commandBarItem23.Command = ReportCommand.VertSpaceMakeEqual;
            this.commandBarItem23.Enabled = false;
            this.commandBarItem23.Hint = "Make the spacing between the selected controls equal";
            this.commandBarItem23.Id = 0x1a;
            this.commandBarItem23.ImageIndex = 0x20;
            this.commandBarItem23.Name = "commandBarItem23";
            this.commandBarItem24.Caption = "&Increase";
            this.commandBarItem24.Command = ReportCommand.VertSpaceIncrease;
            this.commandBarItem24.Enabled = false;
            this.commandBarItem24.Hint = "Increase the spacing between the selected controls";
            this.commandBarItem24.Id = 0x1b;
            this.commandBarItem24.ImageIndex = 0x21;
            this.commandBarItem24.Name = "commandBarItem24";
            this.commandBarItem25.Caption = "&Decrease";
            this.commandBarItem25.Command = ReportCommand.VertSpaceDecrease;
            this.commandBarItem25.Enabled = false;
            this.commandBarItem25.Hint = "Decrease the spacing between the selected controls";
            this.commandBarItem25.Id = 0x1c;
            this.commandBarItem25.ImageIndex = 0x22;
            this.commandBarItem25.Name = "commandBarItem25";
            this.commandBarItem26.Caption = "&Remove";
            this.commandBarItem26.Command = ReportCommand.VertSpaceConcatenate;
            this.commandBarItem26.Enabled = false;
            this.commandBarItem26.Hint = "Remove the spacing between the selected controls";
            this.commandBarItem26.Id = 0x1d;
            this.commandBarItem26.ImageIndex = 0x23;
            this.commandBarItem26.Name = "commandBarItem26";
            this.barSubItem13.Caption = "&Center in Form";
            this.barSubItem13.Id = 0x3a;
            this.barSubItem13.LinksPersistInfo.AddRange(new LinkPersistInfo[] { new LinkPersistInfo(this.commandBarItem27, true), new LinkPersistInfo(this.commandBarItem28) });
            this.barSubItem13.Name = "barSubItem13";
            this.commandBarItem27.Caption = "&Horizontally";
            this.commandBarItem27.Command = ReportCommand.CenterHorizontally;
            this.commandBarItem27.Enabled = false;
            this.commandBarItem27.Hint = "Horizontally center the selected controls within a band";
            this.commandBarItem27.Id = 30;
            this.commandBarItem27.ImageIndex = 0x24;
            this.commandBarItem27.Name = "commandBarItem27";
            this.commandBarItem28.Caption = "&Vertically";
            this.commandBarItem28.Command = ReportCommand.CenterVertically;
            this.commandBarItem28.Enabled = false;
            this.commandBarItem28.Hint = "Vertically center the selected controls within a band";
            this.commandBarItem28.Id = 0x1f;
            this.commandBarItem28.ImageIndex = 0x25;
            this.commandBarItem28.Name = "commandBarItem28";
            this.barSubItem14.Caption = "&Order";
            this.barSubItem14.Id = 0x3b;
            this.barSubItem14.LinksPersistInfo.AddRange(new LinkPersistInfo[] { new LinkPersistInfo(this.commandBarItem29, true), new LinkPersistInfo(this.commandBarItem30) });
            this.barSubItem14.Name = "barSubItem14";
            this.commandBarItem29.Caption = "&Bring to Front";
            this.commandBarItem29.Command = ReportCommand.BringToFront;
            this.commandBarItem29.Enabled = false;
            this.commandBarItem29.Hint = "Bring the selected controls to the front";
            this.commandBarItem29.Id = 0x20;
            this.commandBarItem29.ImageIndex = 0x26;
            this.commandBarItem29.Name = "commandBarItem29";
            this.commandBarItem30.Caption = "&Send to Back";
            this.commandBarItem30.Command = ReportCommand.SendToBack;
            this.commandBarItem30.Enabled = false;
            this.commandBarItem30.Hint = "Move the selected controls to the back";
            this.commandBarItem30.Id = 0x21;
            this.commandBarItem30.ImageIndex = 0x27;
            this.commandBarItem30.Name = "commandBarItem30";
            this.bsiLookAndFeel.Caption = "&Look and Feel";
            this.bsiLookAndFeel.Id = 0x41;
            this.bsiLookAndFeel.Name = "bsiLookAndFeel";
            this.designBar2.BarName = "ToolBar";
            this.designBar2.DockCol = 0;
            this.designBar2.DockRow = 1;
            this.designBar2.DockStyle = BarDockStyle.Top;
            this.designBar2.LinksPersistInfo.AddRange(new LinkPersistInfo[] { new LinkPersistInfo(this.commandBarItem31), new LinkPersistInfo(this.commandBarItem32), new LinkPersistInfo(this.commandBarItem33), new LinkPersistInfo(this.commandBarItem34, true), new LinkPersistInfo(this.commandBarItem35), new LinkPersistInfo(this.commandBarItem36), new LinkPersistInfo(this.commandBarItem37, true), new LinkPersistInfo(this.commandBarItem38) });
            this.designBar2.Text = "Main Toolbar";
            this.designBar3.BarName = "FormattingToolBar";
            this.designBar3.DockCol = 1;
            this.designBar3.DockRow = 1;
            this.designBar3.DockStyle = BarDockStyle.Top;
            this.designBar3.LinksPersistInfo.AddRange(new LinkPersistInfo[] { new LinkPersistInfo(this.barEditItem1), new LinkPersistInfo(this.barEditItem2), new LinkPersistInfo(this.commandBarItem1), new LinkPersistInfo(this.commandBarItem2), new LinkPersistInfo(this.commandBarItem3), new LinkPersistInfo(this.commandColorBarItem1, true), new LinkPersistInfo(this.commandColorBarItem2), new LinkPersistInfo(this.commandBarItem4, true), new LinkPersistInfo(this.commandBarItem5), new LinkPersistInfo(this.commandBarItem6), new LinkPersistInfo(this.commandBarItem7) });
            this.designBar3.Text = "Formatting Toolbar";
            this.barEditItem1.Caption = "Font Name";
            this.barEditItem1.Edit = this.ricbFontName;
            this.barEditItem1.Hint = "Font Name";
            this.barEditItem1.Id = 0;
            this.barEditItem1.Name = "barEditItem1";
            this.barEditItem1.Width = 120;
            this.ricbFontName.AutoHeight = false;
            this.ricbFontName.Buttons.AddRange(new EditorButton[] { new EditorButton(ButtonPredefines.Combo) });
            this.ricbFontName.DropDownRows = 12;
            this.ricbFontName.Name = "ricbFontName";
            this.barEditItem2.Caption = "Font Size";
            this.barEditItem2.Edit = this.ricbFontSize;
            this.barEditItem2.Hint = "Font Size";
            this.barEditItem2.Id = 1;
            this.barEditItem2.Name = "barEditItem2";
            this.barEditItem2.Width = 0x37;
            this.ricbFontSize.AutoHeight = false;
            this.ricbFontSize.Buttons.AddRange(new EditorButton[] { new EditorButton(ButtonPredefines.Combo) });
            this.ricbFontSize.Items.AddRange(new object[] { (byte) 8, (byte) 9, (byte) 10, (byte) 11, (byte) 12, (byte) 14, (byte) 0x10, (byte) 0x12, (byte) 20, (byte) 0x16, (byte) 0x18, (byte) 0x1a, (byte) 0x1c, (byte) 0x24, (byte) 0x30, (byte) 0x48 });
            this.ricbFontSize.Name = "ricbFontSize";
            this.designBar4.BarName = "LayoutToolBar";
            this.designBar4.DockCol = 0;
            this.designBar4.DockRow = 2;
            this.designBar4.DockStyle = BarDockStyle.Top;
            this.designBar4.LinksPersistInfo.AddRange(new LinkPersistInfo[] { 
                new LinkPersistInfo(this.commandBarItem8), new LinkPersistInfo(this.commandBarItem9, true), new LinkPersistInfo(this.commandBarItem10), new LinkPersistInfo(this.commandBarItem11), new LinkPersistInfo(this.commandBarItem12, true), new LinkPersistInfo(this.commandBarItem13), new LinkPersistInfo(this.commandBarItem14), new LinkPersistInfo(this.commandBarItem15, true), new LinkPersistInfo(this.commandBarItem16), new LinkPersistInfo(this.commandBarItem17), new LinkPersistInfo(this.commandBarItem18), new LinkPersistInfo(this.commandBarItem19, true), new LinkPersistInfo(this.commandBarItem20), new LinkPersistInfo(this.commandBarItem21), new LinkPersistInfo(this.commandBarItem22), new LinkPersistInfo(this.commandBarItem23, true),
                new LinkPersistInfo(this.commandBarItem24), new LinkPersistInfo(this.commandBarItem25), new LinkPersistInfo(this.commandBarItem26), new LinkPersistInfo(this.commandBarItem27, true), new LinkPersistInfo(this.commandBarItem28), new LinkPersistInfo(this.commandBarItem29, true), new LinkPersistInfo(this.commandBarItem30)
            });
            this.designBar4.Text = "Layout Toolbar";
            this.designBar5.BarName = "StatusBar";
            this.designBar5.CanDockStyle = BarCanDockStyle.Bottom;
            this.designBar5.DockCol = 0;
            this.designBar5.DockRow = 0;
            this.designBar5.DockStyle = BarDockStyle.Bottom;
            this.designBar5.LinksPersistInfo.AddRange(new LinkPersistInfo[] { new LinkPersistInfo(this.barStaticItem1) });
            this.designBar5.OptionsBar.AllowQuickCustomization = false;
            this.designBar5.OptionsBar.DrawDragBorder = false;
            this.designBar5.OptionsBar.UseWholeRow = true;
            this.designBar5.Text = "Status Bar";
            this.barStaticItem1.AutoSize = BarStaticItemSize.Spring;
            this.barStaticItem1.Id = 0x2a;
            this.barStaticItem1.Name = "barStaticItem1";
            this.barStaticItem1.TextAlignment = StringAlignment.Near;
            this.barStaticItem1.Width = 0x20;
            this.designBar6.BarName = "Zoom Bar";
            this.designBar6.DockCol = 1;
            this.designBar6.DockRow = 2;
            this.designBar6.DockStyle = BarDockStyle.Top;
            this.designBar6.LinksPersistInfo.AddRange(new LinkPersistInfo[] { new LinkPersistInfo(this.commandBarItem44), new LinkPersistInfo(this.commandBarItem45) });
            this.designBar6.Text = "Zoom Bar";
            this.commandBarItem44.Caption = "Zoom Out";
            this.commandBarItem44.Command = ReportCommand.ZoomOut;
            this.commandBarItem44.Enabled = false;
            this.commandBarItem44.Hint = "Zoom out the design surface";
            this.commandBarItem44.Id = 0x42;
            this.commandBarItem44.ImageIndex = 40;
            this.commandBarItem44.ItemShortcut = new BarShortcut(Keys.Control | Keys.Subtract);
            this.commandBarItem44.Name = "commandBarItem44";
            //this.xrZoomBarEditItem1.Caption = "Zoom";
            //this.xrZoomBarEditItem1.Edit = this.designRepositoryItemComboBox1;
            //this.xrZoomBarEditItem1.Enabled = false;
            //this.xrZoomBarEditItem1.Hint = "Select or input the zoom factor";
            //this.xrZoomBarEditItem1.Id = 0x43;
            //this.xrZoomBarEditItem1.Name = "xrZoomBarEditItem1";
            //this.xrZoomBarEditItem1.Width = 70;
            this.designRepositoryItemComboBox1.AutoComplete = false;
            this.designRepositoryItemComboBox1.Buttons.AddRange(new EditorButton[] { new EditorButton(ButtonPredefines.Combo) });
            this.designRepositoryItemComboBox1.Name = "designRepositoryItemComboBox1";
            this.commandBarItem45.Caption = "Zoom In";
            this.commandBarItem45.Command = ReportCommand.ZoomIn;
            this.commandBarItem45.Enabled = false;
            this.commandBarItem45.Hint = "Zoom in the design surface";
            this.commandBarItem45.Id = 0x44;
            this.commandBarItem45.ImageIndex = 0x29;
            this.commandBarItem45.ItemShortcut = new BarShortcut(Keys.Control | Keys.Add);
            this.commandBarItem45.Name = "commandBarItem45";
            this.xrDesignDockManager1.Form = this;
            this.xrDesignDockManager1.ImageStream = (ImageCollectionStreamer) manager.GetObject("xrDesignDockManager1.ImageStream");
            this.xrDesignDockManager1.RootPanels.AddRange(new DockPanel[] { this.panelContainer1, this.toolBoxDockPanel1, this.groupAndSortDockPanel1 });
            this.xrDesignDockManager1.TopZIndexControls.AddRange(new string[] { "DevExpress.XtraBars.BarDockControl", "System.Windows.Forms.StatusBar" });
            this.xrDesignDockManager1.XRDesignPanel = base.xrDesignPanel;
            this.panelContainer1.Controls.Add(this.panelContainer2);
            this.panelContainer1.Controls.Add(this.propertyGridDockPanel1);
            this.panelContainer1.Dock = DockingStyle.Right;
            this.panelContainer1.ID = new Guid("c924e71d-fc07-4f71-80db-150e46515172");
            this.panelContainer1.Location = new Point(0x278, 0x4e);
            this.panelContainer1.Name = "panelContainer1";
            this.panelContainer1.OriginalSize = new Size(200, 200);
            this.panelContainer1.Size = new Size(200, 0x1d1);
            this.panelContainer1.Text = "panelContainer1";
            this.panelContainer2.ActiveChild = this.reportExplorerDockPanel1;
            this.panelContainer2.Controls.Add(this.reportExplorerDockPanel1);
            this.panelContainer2.Controls.Add(this.fieldListDockPanel1);
            this.panelContainer2.Dock = DockingStyle.Fill;
            this.panelContainer2.ID = new Guid("f590a4cc-96cf-4036-aaa1-6a23922194fc");
            this.panelContainer2.ImageIndex = 3;
            this.panelContainer2.Location = new Point(0, 0);
            this.panelContainer2.Name = "panelContainer2";
            this.panelContainer2.OriginalSize = new Size(200, 0x445);
            this.panelContainer2.Size = new Size(200, 0x77d);
            this.panelContainer2.Tabbed = true;
            this.panelContainer2.Text = "panelContainer2";
            this.reportExplorerDockPanel1.Controls.Add(this.reportExplorerDockPanel1_Container);
            this.reportExplorerDockPanel1.Dock = DockingStyle.Fill;
            this.reportExplorerDockPanel1.ID = new Guid("fb3ec6cc-3b9b-4b9c-91cf-cff78c1edbf1");
            this.reportExplorerDockPanel1.ImageIndex = 3;
            this.reportExplorerDockPanel1.Location = new Point(3, 0x19);
            this.reportExplorerDockPanel1.Name = "reportExplorerDockPanel1";
            this.reportExplorerDockPanel1.OriginalSize = new Size(0xc2, 0x412);
            this.reportExplorerDockPanel1.Size = new Size(0xc2, 0x74a);
            this.reportExplorerDockPanel1.Text = "Report Explorer";
            this.reportExplorerDockPanel1.XRDesignPanel = base.xrDesignPanel;
            this.reportExplorerDockPanel1_Container.Location = new Point(0, 0);
            this.reportExplorerDockPanel1_Container.Name = "reportExplorerDockPanel1_Container";
            this.reportExplorerDockPanel1_Container.Size = new Size(0xc2, 0x74a);
            this.reportExplorerDockPanel1_Container.TabIndex = 0;
            this.fieldListDockPanel1.Controls.Add(this.fieldListDockPanel1_Container);
            this.fieldListDockPanel1.Dock = DockingStyle.Fill;
            this.fieldListDockPanel1.ID = new Guid("faf69838-a93f-4114-83e8-d0d09cc5ce95");
            this.fieldListDockPanel1.ImageIndex = 0;
            this.fieldListDockPanel1.Location = new Point(3, 0x19);
            this.fieldListDockPanel1.Name = "fieldListDockPanel1";
            this.fieldListDockPanel1.OriginalSize = new Size(0xc2, 0x412);
            this.fieldListDockPanel1.Size = new Size(0xc2, 0x74a);
            this.fieldListDockPanel1.Text = "Field List";
            this.fieldListDockPanel1.XRDesignPanel = base.xrDesignPanel;
            this.fieldListDockPanel1_Container.Location = new Point(0, 0);
            this.fieldListDockPanel1_Container.Name = "fieldListDockPanel1_Container";
            this.fieldListDockPanel1_Container.Size = new Size(0xc2, 0x74a);
            this.fieldListDockPanel1_Container.TabIndex = 0;
            this.propertyGridDockPanel1.Controls.Add(this.propertyGridDockPanel1_Container);
            this.propertyGridDockPanel1.Dock = DockingStyle.Fill;
            this.propertyGridDockPanel1.ID = new Guid("b38d12c3-cd06-4dec-b93d-63a0088e495a");
            this.propertyGridDockPanel1.ImageIndex = 2;
            this.propertyGridDockPanel1.Location = new Point(0, 0x77d);
            this.propertyGridDockPanel1.Name = "propertyGridDockPanel1";
            this.propertyGridDockPanel1.OriginalSize = new Size(200, 0);
            this.propertyGridDockPanel1.Size = new Size(200, 0);
            this.propertyGridDockPanel1.Text = "Property Grid";
            this.propertyGridDockPanel1.XRDesignPanel = base.xrDesignPanel;
            this.propertyGridDockPanel1_Container.Location = new Point(3, -1452);
            this.propertyGridDockPanel1_Container.Name = "propertyGridDockPanel1_Container";
            this.propertyGridDockPanel1_Container.Size = new Size(0xc2, 0);
            this.propertyGridDockPanel1_Container.TabIndex = 0;
            this.toolBoxDockPanel1.Controls.Add(this.toolBoxDockPanel1_Container);
            this.toolBoxDockPanel1.Dock = DockingStyle.Left;
            this.toolBoxDockPanel1.ID = new Guid("161a5a1a-d9b9-4f06-9ac4-d0c3e507c54f");
            this.toolBoxDockPanel1.ImageIndex = 4;
            this.toolBoxDockPanel1.Location = new Point(0, 0x4e);
            this.toolBoxDockPanel1.Name = "toolBoxDockPanel1";
            this.toolBoxDockPanel1.OriginalSize = new Size(200, 200);
            this.toolBoxDockPanel1.Size = new Size(200, 0x1d1);
            this.toolBoxDockPanel1.Text = "Tool Box";
            this.toolBoxDockPanel1.XRDesignPanel = base.xrDesignPanel;
            this.toolBoxDockPanel1_Container.Location = new Point(3, 0x19);
            this.toolBoxDockPanel1_Container.Name = "toolBoxDockPanel1_Container";
            this.toolBoxDockPanel1_Container.Size = new Size(0xc2, 0x1b5);
            this.toolBoxDockPanel1_Container.TabIndex = 0;
            this.groupAndSortDockPanel1.Controls.Add(this.groupAndSortDockPanel1_Container);
            this.groupAndSortDockPanel1.Dock = DockingStyle.Bottom;
            this.groupAndSortDockPanel1.ID = new Guid("4bab159e-c495-4d67-87dc-f4e895da443e");
            this.groupAndSortDockPanel1.ImageIndex = 1;
            this.groupAndSortDockPanel1.Location = new Point(200, 0x157);
            this.groupAndSortDockPanel1.Name = "groupAndSortDockPanel1";
            this.groupAndSortDockPanel1.OriginalSize = new Size(200, 200);
            this.groupAndSortDockPanel1.Size = new Size(0x1b0, 200);
            this.groupAndSortDockPanel1.Text = "Group and Sort";
            this.groupAndSortDockPanel1.XRDesignPanel = base.xrDesignPanel;
            this.groupAndSortDockPanel1_Container.Location = new Point(3, 0x19);
            this.groupAndSortDockPanel1_Container.Name = "groupAndSortDockPanel1_Container";
            this.groupAndSortDockPanel1_Container.Size = new Size(0x1aa, 0xac);
            this.groupAndSortDockPanel1_Container.TabIndex = 0;
            base.ClientSize = new Size(0x340, 0x23b);
            base.Controls.Add(this.groupAndSortDockPanel1);
            base.Controls.Add(this.toolBoxDockPanel1);
            base.Controls.Add(this.panelContainer1);
            base.Controls.Add(this.barDockControlLeft);
            base.Controls.Add(this.barDockControlRight);
            base.Controls.Add(this.barDockControlBottom);
            base.Controls.Add(this.barDockControlTop);
            base.Name = "CustomDesignForm";
            base.Load += new EventHandler(this.CustomDesignForm_Load);
            base.Controls.SetChildIndex(this.barDockControlTop, 0);
            base.Controls.SetChildIndex(this.barDockControlBottom, 0);
            base.Controls.SetChildIndex(this.barDockControlRight, 0);
            base.Controls.SetChildIndex(this.barDockControlLeft, 0);
            base.Controls.SetChildIndex(this.panelContainer1, 0);
            base.Controls.SetChildIndex(this.toolBoxDockPanel1, 0);
            base.Controls.SetChildIndex(this.groupAndSortDockPanel1, 0);
            base.Controls.SetChildIndex(base.xrDesignPanel, 0);
            base.xrDesignPanel.EndInit();
            this.xrDesignBarManager1.EndInit();
            this.ricbFontName.EndInit();
            this.ricbFontSize.EndInit();
            this.designRepositoryItemComboBox1.EndInit();
            this.xrDesignDockManager1.EndInit();
            this.panelContainer1.ResumeLayout(false);
            this.panelContainer2.ResumeLayout(false);
            this.reportExplorerDockPanel1.ResumeLayout(false);
            this.fieldListDockPanel1.ResumeLayout(false);
            this.propertyGridDockPanel1.ResumeLayout(false);
            this.toolBoxDockPanel1.ResumeLayout(false);
            this.groupAndSortDockPanel1.ResumeLayout(false);
            base.ResumeLayout(false);
        }

        protected override void RestoreLayout()
        {
        }

        protected override void SaveLayout()
        {
        }
    }
}

