namespace Vssoft.Common.Report
{
    using DevExpress.Utils;
    using DevExpress.XtraBars;
    using DevExpress.XtraBars.Ribbon;
    using DevExpress.XtraCharts;
    using DevExpress.XtraEditors.Controls;
    using DevExpress.XtraEditors.Repository;
    using DevExpress.XtraGrid;
    using DevExpress.XtraPrinting;
    using DevExpress.XtraPrinting.Control;
    using DevExpress.XtraPrinting.Preview;
    using DevExpress.XtraReports.UI;
    using DevExpress.XtraTreeList;
    using Vssoft.Common;
    using Vssoft.Common;
    using System;
    using System.ComponentModel;
    using System.Drawing;
    using System.Windows.Forms;

    public class xfmReport : RibbonForm
    {
        private BarButtonItem barButtonItem1;
        private BarStaticItem barStaticItem1;
        private PrintPreviewBarItem bbiBookmarks;
        private PrintPreviewBarItem bbiClosePrintPreview;
        private BarButtonItem bbiDesignView;
        private PrintPreviewBarItem bbiEmailAs;
        private PrintPreviewBarItem bbiExportTo;
        private PrintPreviewBarItem bbiFind;
        private PrintPreviewBarItem bbiFirstPage;
        private PrintPreviewBarItem bbiHandTool;
        private PrintPreviewBarItem bbiHeaderFooter;
        private PrintPreviewBarItem bbiLastPage;
        private PrintPreviewBarItem bbiMagnifier;
        private PrintPreviewBarItem bbiManyPages;
        private PrintPreviewBarItem bbiMargins;
        private PrintPreviewBarItem bbiNextPage;
        private PrintPreviewBarItem bbiOpen;
        private PrintPreviewBarItem bbiOptions;
        private PrintPreviewBarItem bbiOrientation;
        private PrintPreviewBarItem bbiPageColor;
        private PrintPreviewBarItem bbiParameters;
        private PrintPreviewBarItem bbiPointer;
        private PrintPreviewBarItem bbiPreviousPage;
        private PrintPreviewBarItem bbiPrint;
        private PrintPreviewBarItem bbiQuickPrint;
        private PrintPreviewBarItem bbiSave;
        private PrintPreviewBarItem bbiScale;
        private PrintPreviewBarItem bbiSize;
        private PrintPreviewBarItem bbiWatermark;
        private PrintPreviewBarItem bbiZoom;
        private PrintPreviewBarItem bbiZoomIn;
        private PrintPreviewBarItem bbiZoomOut;
        private IContainer components;
        private DevExpress.Utils.ImageCollection imageCollection1;
        private XtraReport m_xtraReport;
        private PrintControl printControl1;
        private PrintPreviewBarItem printPreviewBarItem29;
        private PrintPreviewBarItem printPreviewBarItem30;
        private PrintPreviewBarItem printPreviewBarItem31;
        private PrintPreviewBarItem printPreviewBarItem32;
        private PrintPreviewBarItem printPreviewBarItem33;
        private PrintPreviewBarItem printPreviewBarItem34;
        private PrintPreviewBarItem printPreviewBarItem35;
        private PrintPreviewBarItem printPreviewBarItem36;
        private PrintPreviewBarItem printPreviewBarItem37;
        private PrintPreviewBarItem printPreviewBarItem38;
        private PrintPreviewBarItem printPreviewBarItem39;
        private PrintPreviewBarItem printPreviewBarItem40;
        private PrintPreviewBarItem printPreviewBarItem41;
        private PrintPreviewBarItem printPreviewBarItem42;
        private PrintPreviewBarItem printPreviewBarItem43;
        private PrintPreviewBarItem printPreviewBarItem44;
        private PrintPreviewBarItem printPreviewBarItem45;
        private PrintPreviewBarItem printPreviewBarItem48;
        private PrintPreviewBarItem printPreviewBarItem7;
        private PrintPreviewStaticItem printPreviewStaticItem1;
        private PrintPreviewStaticItem printPreviewStaticItem2;
        private PrintRibbonController printRibbonController1;
        private ProgressBarEditItem progressBarEditItem1;
        private PrintPreviewRibbonPage rbgpPrintPreview;
        private PrintPreviewRibbonPageGroup rbpDocument;
        private PrintPreviewRibbonPageGroup rbpExport;
        private PrintPreviewRibbonPageGroup rbpNavigation;
        private PrintPreviewRibbonPageGroup rbpPageBackground;
        private PrintPreviewRibbonPageGroup rbpPageSetup;
        private PrintPreviewRibbonPageGroup rbpPrint;
        private PrintPreviewRibbonPageGroup rbpZoom;
        private RepositoryItemProgressBar repositoryItemProgressBar1;
        private RepositoryItemZoomTrackBar repositoryItemZoomTrackBar1;
        private RibbonControl ribbonControl1;
        private RibbonStatusBar ribbonStatusBar1;
        private ZoomTrackBarEditItem zoomTrackBarEditItem1;

        public xfmReport()
        {
            this.components = null;
            this.InitializeComponent();
            this.InitMultiLanguages();
        }

        public xfmReport(string Title)
        {
            this.components = null;
            this.InitializeComponent();
            this.InitMultiLanguages();
            this.Text = Title + " (B\x00e1o C\x00e1o - Perfect HRM 2012)";
        }

        private void bbiDesignView_ItemClick(object sender, ItemClickEventArgs e)
        {
            new xfmReportDesigner(this.m_xtraReport).Show();
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing && (this.components != null))
            {
                this.components.Dispose();
            }
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            this.components = new Container();
            ComponentResourceManager manager = new ComponentResourceManager(typeof(xfmReport));
            SuperToolTip tip = new SuperToolTip();
            ToolTipTitleItem item = new ToolTipTitleItem();
            ToolTipItem item2 = new ToolTipItem();
            SuperToolTip tip2 = new SuperToolTip();
            ToolTipTitleItem item3 = new ToolTipTitleItem();
            ToolTipItem item4 = new ToolTipItem();
            SuperToolTip tip3 = new SuperToolTip();
            ToolTipTitleItem item5 = new ToolTipTitleItem();
            ToolTipItem item6 = new ToolTipItem();
            SuperToolTip tip4 = new SuperToolTip();
            ToolTipTitleItem item7 = new ToolTipTitleItem();
            ToolTipItem item8 = new ToolTipItem();
            SuperToolTip tip5 = new SuperToolTip();
            ToolTipTitleItem item9 = new ToolTipTitleItem();
            ToolTipItem item10 = new ToolTipItem();
            SuperToolTip tip6 = new SuperToolTip();
            ToolTipTitleItem item11 = new ToolTipTitleItem();
            ToolTipItem item12 = new ToolTipItem();
            SuperToolTip tip7 = new SuperToolTip();
            ToolTipTitleItem item13 = new ToolTipTitleItem();
            ToolTipItem item14 = new ToolTipItem();
            SuperToolTip tip8 = new SuperToolTip();
            ToolTipTitleItem item15 = new ToolTipTitleItem();
            ToolTipItem item16 = new ToolTipItem();
            SuperToolTip tip9 = new SuperToolTip();
            ToolTipTitleItem item17 = new ToolTipTitleItem();
            ToolTipItem item18 = new ToolTipItem();
            SuperToolTip tip10 = new SuperToolTip();
            ToolTipTitleItem item19 = new ToolTipTitleItem();
            ToolTipItem item20 = new ToolTipItem();
            SuperToolTip tip11 = new SuperToolTip();
            ToolTipTitleItem item21 = new ToolTipTitleItem();
            ToolTipItem item22 = new ToolTipItem();
            SuperToolTip tip12 = new SuperToolTip();
            ToolTipTitleItem item23 = new ToolTipTitleItem();
            ToolTipItem item24 = new ToolTipItem();
            SuperToolTip tip13 = new SuperToolTip();
            ToolTipTitleItem item25 = new ToolTipTitleItem();
            ToolTipItem item26 = new ToolTipItem();
            SuperToolTip tip14 = new SuperToolTip();
            ToolTipTitleItem item27 = new ToolTipTitleItem();
            ToolTipItem item28 = new ToolTipItem();
            SuperToolTip tip15 = new SuperToolTip();
            ToolTipTitleItem item29 = new ToolTipTitleItem();
            ToolTipItem item30 = new ToolTipItem();
            SuperToolTip tip16 = new SuperToolTip();
            ToolTipTitleItem item31 = new ToolTipTitleItem();
            ToolTipItem item32 = new ToolTipItem();
            SuperToolTip tip17 = new SuperToolTip();
            ToolTipTitleItem item33 = new ToolTipTitleItem();
            ToolTipItem item34 = new ToolTipItem();
            SuperToolTip tip18 = new SuperToolTip();
            ToolTipTitleItem item35 = new ToolTipTitleItem();
            ToolTipItem item36 = new ToolTipItem();
            SuperToolTip tip19 = new SuperToolTip();
            ToolTipTitleItem item37 = new ToolTipTitleItem();
            ToolTipItem item38 = new ToolTipItem();
            SuperToolTip tip20 = new SuperToolTip();
            ToolTipTitleItem item39 = new ToolTipTitleItem();
            ToolTipItem item40 = new ToolTipItem();
            SuperToolTip tip21 = new SuperToolTip();
            ToolTipTitleItem item41 = new ToolTipTitleItem();
            ToolTipItem item42 = new ToolTipItem();
            SuperToolTip tip22 = new SuperToolTip();
            ToolTipTitleItem item43 = new ToolTipTitleItem();
            ToolTipItem item44 = new ToolTipItem();
            SuperToolTip tip23 = new SuperToolTip();
            ToolTipTitleItem item45 = new ToolTipTitleItem();
            ToolTipItem item46 = new ToolTipItem();
            SuperToolTip tip24 = new SuperToolTip();
            ToolTipTitleItem item47 = new ToolTipTitleItem();
            ToolTipItem item48 = new ToolTipItem();
            SuperToolTip tip25 = new SuperToolTip();
            ToolTipTitleItem item49 = new ToolTipTitleItem();
            ToolTipItem item50 = new ToolTipItem();
            SuperToolTip tip26 = new SuperToolTip();
            ToolTipTitleItem item51 = new ToolTipTitleItem();
            ToolTipItem item52 = new ToolTipItem();
            SuperToolTip tip27 = new SuperToolTip();
            ToolTipTitleItem item53 = new ToolTipTitleItem();
            ToolTipItem item54 = new ToolTipItem();
            SuperToolTip tip28 = new SuperToolTip();
            ToolTipTitleItem item55 = new ToolTipTitleItem();
            ToolTipItem item56 = new ToolTipItem();
            SuperToolTip tip29 = new SuperToolTip();
            ToolTipTitleItem item57 = new ToolTipTitleItem();
            ToolTipItem item58 = new ToolTipItem();
            SuperToolTip tip30 = new SuperToolTip();
            ToolTipTitleItem item59 = new ToolTipTitleItem();
            ToolTipItem item60 = new ToolTipItem();
            SuperToolTip tip31 = new SuperToolTip();
            ToolTipTitleItem item61 = new ToolTipTitleItem();
            ToolTipItem item62 = new ToolTipItem();
            SuperToolTip tip32 = new SuperToolTip();
            ToolTipTitleItem item63 = new ToolTipTitleItem();
            ToolTipItem item64 = new ToolTipItem();
            SuperToolTip tip33 = new SuperToolTip();
            ToolTipTitleItem item65 = new ToolTipTitleItem();
            ToolTipItem item66 = new ToolTipItem();
            SuperToolTip tip34 = new SuperToolTip();
            ToolTipTitleItem item67 = new ToolTipTitleItem();
            ToolTipItem item68 = new ToolTipItem();
            SuperToolTip tip35 = new SuperToolTip();
            ToolTipTitleItem item69 = new ToolTipTitleItem();
            ToolTipItem item70 = new ToolTipItem();
            SuperToolTip tip36 = new SuperToolTip();
            ToolTipTitleItem item71 = new ToolTipTitleItem();
            ToolTipItem item72 = new ToolTipItem();
            SuperToolTip tip37 = new SuperToolTip();
            ToolTipTitleItem item73 = new ToolTipTitleItem();
            ToolTipItem item74 = new ToolTipItem();
            SuperToolTip tip38 = new SuperToolTip();
            ToolTipTitleItem item75 = new ToolTipTitleItem();
            ToolTipItem item76 = new ToolTipItem();
            SuperToolTip tip39 = new SuperToolTip();
            ToolTipTitleItem item77 = new ToolTipTitleItem();
            ToolTipItem item78 = new ToolTipItem();
            SuperToolTip tip40 = new SuperToolTip();
            ToolTipTitleItem item79 = new ToolTipTitleItem();
            ToolTipItem item80 = new ToolTipItem();
            SuperToolTip tip41 = new SuperToolTip();
            ToolTipTitleItem item81 = new ToolTipTitleItem();
            ToolTipItem item82 = new ToolTipItem();
            SuperToolTip tip42 = new SuperToolTip();
            ToolTipTitleItem item83 = new ToolTipTitleItem();
            ToolTipItem item84 = new ToolTipItem();
            SuperToolTip tip43 = new SuperToolTip();
            ToolTipTitleItem item85 = new ToolTipTitleItem();
            ToolTipItem item86 = new ToolTipItem();
            SuperToolTip tip44 = new SuperToolTip();
            ToolTipTitleItem item87 = new ToolTipTitleItem();
            ToolTipItem item88 = new ToolTipItem();
            SuperToolTip tip45 = new SuperToolTip();
            ToolTipTitleItem item89 = new ToolTipTitleItem();
            ToolTipItem item90 = new ToolTipItem();
            SuperToolTip tip46 = new SuperToolTip();
            ToolTipTitleItem item91 = new ToolTipTitleItem();
            ToolTipItem item92 = new ToolTipItem();
            SuperToolTip tip47 = new SuperToolTip();
            ToolTipTitleItem item93 = new ToolTipTitleItem();
            ToolTipItem item94 = new ToolTipItem();
            SuperToolTip tip48 = new SuperToolTip();
            ToolTipTitleItem item95 = new ToolTipTitleItem();
            ToolTipItem item96 = new ToolTipItem();
            this.printRibbonController1 = new PrintRibbonController();
            this.printControl1 = new PrintControl();
            this.ribbonControl1 = new RibbonControl();
            this.imageCollection1 = new DevExpress.Utils.ImageCollection(this.components);
            this.bbiBookmarks = new PrintPreviewBarItem();
            this.bbiParameters = new PrintPreviewBarItem();
            this.bbiFind = new PrintPreviewBarItem();
            this.bbiOptions = new PrintPreviewBarItem();
            this.bbiPrint = new PrintPreviewBarItem();
            this.bbiQuickPrint = new PrintPreviewBarItem();
            this.printPreviewBarItem7 = new PrintPreviewBarItem();
            this.bbiHeaderFooter = new PrintPreviewBarItem();
            this.bbiScale = new PrintPreviewBarItem();
            this.bbiPointer = new PrintPreviewBarItem();
            this.bbiHandTool = new PrintPreviewBarItem();
            this.bbiMagnifier = new PrintPreviewBarItem();
            this.bbiZoomOut = new PrintPreviewBarItem();
            this.bbiZoomIn = new PrintPreviewBarItem();
            this.bbiZoom = new PrintPreviewBarItem();
            this.bbiFirstPage = new PrintPreviewBarItem();
            this.bbiPreviousPage = new PrintPreviewBarItem();
            this.bbiNextPage = new PrintPreviewBarItem();
            this.bbiLastPage = new PrintPreviewBarItem();
            this.bbiManyPages = new PrintPreviewBarItem();
            this.bbiPageColor = new PrintPreviewBarItem();
            this.bbiWatermark = new PrintPreviewBarItem();
            this.bbiExportTo = new PrintPreviewBarItem();
            this.bbiEmailAs = new PrintPreviewBarItem();
            this.bbiClosePrintPreview = new PrintPreviewBarItem();
            this.bbiOrientation = new PrintPreviewBarItem();
            this.bbiSize = new PrintPreviewBarItem();
            this.bbiMargins = new PrintPreviewBarItem();
            this.printPreviewBarItem29 = new PrintPreviewBarItem();
            this.printPreviewBarItem30 = new PrintPreviewBarItem();
            this.printPreviewBarItem31 = new PrintPreviewBarItem();
            this.printPreviewBarItem32 = new PrintPreviewBarItem();
            this.printPreviewBarItem33 = new PrintPreviewBarItem();
            this.printPreviewBarItem34 = new PrintPreviewBarItem();
            this.printPreviewBarItem35 = new PrintPreviewBarItem();
            this.printPreviewBarItem36 = new PrintPreviewBarItem();
            this.printPreviewBarItem37 = new PrintPreviewBarItem();
            this.printPreviewBarItem38 = new PrintPreviewBarItem();
            this.printPreviewBarItem39 = new PrintPreviewBarItem();
            this.printPreviewBarItem40 = new PrintPreviewBarItem();
            this.printPreviewBarItem41 = new PrintPreviewBarItem();
            this.printPreviewBarItem42 = new PrintPreviewBarItem();
            this.printPreviewBarItem43 = new PrintPreviewBarItem();
            this.printPreviewBarItem44 = new PrintPreviewBarItem();
            this.printPreviewBarItem45 = new PrintPreviewBarItem();
            this.bbiOpen = new PrintPreviewBarItem();
            this.bbiSave = new PrintPreviewBarItem();
            this.printPreviewStaticItem1 = new PrintPreviewStaticItem();
            this.barStaticItem1 = new BarStaticItem();
            this.progressBarEditItem1 = new ProgressBarEditItem();
            this.repositoryItemProgressBar1 = new RepositoryItemProgressBar();
            this.printPreviewBarItem48 = new PrintPreviewBarItem();
            this.barButtonItem1 = new BarButtonItem();
            this.printPreviewStaticItem2 = new PrintPreviewStaticItem();
            this.zoomTrackBarEditItem1 = new ZoomTrackBarEditItem();
            this.repositoryItemZoomTrackBar1 = new RepositoryItemZoomTrackBar();
            this.bbiDesignView = new BarButtonItem();
            this.rbgpPrintPreview = new PrintPreviewRibbonPage();
            this.rbpDocument = new PrintPreviewRibbonPageGroup();
            this.rbpPrint = new PrintPreviewRibbonPageGroup();
            this.rbpPageSetup = new PrintPreviewRibbonPageGroup();
            this.rbpNavigation = new PrintPreviewRibbonPageGroup();
            this.rbpZoom = new PrintPreviewRibbonPageGroup();
            this.rbpPageBackground = new PrintPreviewRibbonPageGroup();
            this.rbpExport = new PrintPreviewRibbonPageGroup();
            this.ribbonStatusBar1 = new RibbonStatusBar();
            this.printRibbonController1.BeginInit();
            this.ribbonControl1.BeginInit();
            this.imageCollection1.BeginInit();
            this.repositoryItemProgressBar1.BeginInit();
            this.repositoryItemZoomTrackBar1.BeginInit();
            base.SuspendLayout();
            this.printRibbonController1.PrintControl = this.printControl1;
            this.printRibbonController1.RibbonControl = this.ribbonControl1;
            this.printRibbonController1.RibbonStatusBar = this.ribbonStatusBar1;
            this.printControl1.BackColor = Color.Empty;
            this.printControl1.Dock = DockStyle.Fill;
            this.printControl1.ForeColor = Color.Empty;
            this.printControl1.IsMetric = false;
            this.printControl1.Location = new Point(0, 0x8f);
            this.printControl1.Name = "printControl1";
            this.printControl1.Size = new Size(0x426, 490);
            this.printControl1.TabIndex = 2;
            this.printControl1.TooltipFont = new Font("Tahoma", 8.25f);
            //this.ribbonControl1.ApplicationIcon = Resources.app_Hrm;
            this.ribbonControl1.Images = this.imageCollection1;
            this.ribbonControl1.Items.AddRange(new BarItem[] { 
                this.bbiBookmarks, this.bbiParameters, this.bbiFind, this.bbiOptions, this.bbiPrint, this.bbiQuickPrint, this.printPreviewBarItem7, this.bbiHeaderFooter, this.bbiScale, this.bbiPointer, this.bbiHandTool, this.bbiMagnifier, this.bbiZoomOut, this.bbiZoomIn, this.bbiZoom, this.bbiFirstPage,
                this.bbiPreviousPage, this.bbiNextPage, this.bbiLastPage, this.bbiManyPages, this.bbiPageColor, this.bbiWatermark, this.bbiExportTo, this.bbiEmailAs, this.bbiClosePrintPreview, this.bbiOrientation, this.bbiSize, this.bbiMargins, this.printPreviewBarItem29, this.printPreviewBarItem30, this.printPreviewBarItem31, this.printPreviewBarItem32,
                this.printPreviewBarItem33, this.printPreviewBarItem34, this.printPreviewBarItem35, this.printPreviewBarItem36, this.printPreviewBarItem37, this.printPreviewBarItem38, this.printPreviewBarItem39, this.printPreviewBarItem40, this.printPreviewBarItem41, this.printPreviewBarItem42, this.printPreviewBarItem43, this.printPreviewBarItem44, this.printPreviewBarItem45, this.bbiOpen, this.bbiSave, this.printPreviewStaticItem1,
                this.barStaticItem1, this.progressBarEditItem1, this.printPreviewBarItem48, this.barButtonItem1, this.printPreviewStaticItem2, this.zoomTrackBarEditItem1, this.bbiDesignView
            });
            this.ribbonControl1.Location = new Point(0, 0);
            this.ribbonControl1.MaxItemId = 0x38;
            this.ribbonControl1.Name = "ribbonControl1";
            this.ribbonControl1.Pages.AddRange(new RibbonPage[] { this.rbgpPrintPreview });
            this.ribbonControl1.RepositoryItems.AddRange(new RepositoryItem[] { this.repositoryItemProgressBar1, this.repositoryItemZoomTrackBar1 });
            this.ribbonControl1.SelectedPage = this.rbgpPrintPreview;
            this.ribbonControl1.ShowToolbarCustomizeItem = false;
            this.ribbonControl1.Size = new Size(0x426, 0x8f);
            this.ribbonControl1.StatusBar = this.ribbonStatusBar1;
            this.ribbonControl1.Toolbar.ItemLinks.Add(this.bbiDesignView);
            this.ribbonControl1.Toolbar.ShowCustomizeItem = false;
            this.imageCollection1.ImageStream = (ImageCollectionStreamer) manager.GetObject("imageCollection1.ImageStream");
            this.imageCollection1.Images.SetKeyName(0, "Canvas.png");
            this.bbiBookmarks.ButtonStyle = BarButtonStyle.Check;
            this.bbiBookmarks.Caption = "Đ\x00e1nh Dấu";
            this.bbiBookmarks.Command = PrintingSystemCommand.DocumentMap;
            this.bbiBookmarks.ContextSpecifier = this.printRibbonController1;
            this.bbiBookmarks.Enabled = false;
            this.bbiBookmarks.Glyph = PrintRibbonControllerResources.RibbonPrintPreview_DocumentMap;
            this.bbiBookmarks.Id = 0;
            this.bbiBookmarks.LargeGlyph = PrintRibbonControllerResources.RibbonPrintPreview_DocumentMapLarge;
            this.bbiBookmarks.Name = "bbiBookmarks";
            tip.FixedTooltipWidth = true;
            item.Text = "Đ\x00e1nh dấu t\x00e0i liệu";
            item2.LeftIndent = 6;
            item2.Text = "Open the Document Map, which allows you to navigate through a structural view of the document.";
            tip.Items.Add(item);
            tip.Items.Add(item2);
            tip.MaxWidth = 210;
            this.bbiBookmarks.SuperTip = tip;
            this.bbiParameters.ButtonStyle = BarButtonStyle.Check;
            this.bbiParameters.Caption = "Tham Số";
            this.bbiParameters.Command = PrintingSystemCommand.Parameters;
            this.bbiParameters.ContextSpecifier = this.printRibbonController1;
            this.bbiParameters.Enabled = false;
            this.bbiParameters.Glyph = PrintRibbonControllerResources.RibbonPrintPreview_Parameters;
            this.bbiParameters.Id = 1;
            this.bbiParameters.LargeGlyph = PrintRibbonControllerResources.RibbonPrintPreview_ParametersLarge;
            this.bbiParameters.Name = "bbiParameters";
            tip2.FixedTooltipWidth = true;
            item3.Text = "Tham số";
            item4.LeftIndent = 6;
            item4.Text = "Open the Parameters pane, which allows you to enter values for report parameters.";
            tip2.Items.Add(item3);
            tip2.Items.Add(item4);
            tip2.MaxWidth = 210;
            this.bbiParameters.SuperTip = tip2;
            this.bbiFind.Caption = "T\x00ecm Kiếm";
            this.bbiFind.Command = PrintingSystemCommand.Find;
            this.bbiFind.ContextSpecifier = this.printRibbonController1;
            this.bbiFind.Enabled = false;
            this.bbiFind.Glyph = PrintRibbonControllerResources.RibbonPrintPreview_Find;
            this.bbiFind.Id = 2;
            this.bbiFind.LargeGlyph = PrintRibbonControllerResources.RibbonPrintPreview_FindLarge;
            this.bbiFind.Name = "bbiFind";
            tip3.FixedTooltipWidth = true;
            item5.Text = "T\x00ecm kiếm";
            item6.LeftIndent = 6;
            item6.Text = "Hiển thị hộp thoại t\x00ecm kiếm để t\x00ecm dữ liệu trong trang in.";
            tip3.Items.Add(item5);
            tip3.Items.Add(item6);
            tip3.MaxWidth = 210;
            this.bbiFind.SuperTip = tip3;
            this.bbiOptions.ButtonStyle = BarButtonStyle.Check;
            this.bbiOptions.Caption = "T\x00f9y Chọn";
            this.bbiOptions.Command = PrintingSystemCommand.Customize;
            this.bbiOptions.ContextSpecifier = this.printRibbonController1;
            this.bbiOptions.Enabled = false;
            this.bbiOptions.Glyph = PrintRibbonControllerResources.RibbonPrintPreview_Customize;
            this.bbiOptions.Id = 3;
            this.bbiOptions.LargeGlyph = PrintRibbonControllerResources.RibbonPrintPreview_CustomizeLarge;
            this.bbiOptions.Name = "bbiOptions";
            tip4.FixedTooltipWidth = true;
            item7.Text = "T\x00f9y chọn";
            item8.LeftIndent = 6;
            item8.Text = "Mở hộp thoại t\x00f9y chọn (Print Options dialog), thực hiện c\x00e1c t\x00f9y chọn cho việc in ấn.";
            tip4.Items.Add(item7);
            tip4.Items.Add(item8);
            tip4.MaxWidth = 210;
            this.bbiOptions.SuperTip = tip4;
            this.bbiPrint.ButtonStyle = BarButtonStyle.Check;
            this.bbiPrint.Caption = "In...";
            this.bbiPrint.Command = PrintingSystemCommand.Print;
            this.bbiPrint.ContextSpecifier = this.printRibbonController1;
            this.bbiPrint.Enabled = false;
            this.bbiPrint.Glyph = PrintRibbonControllerResources.RibbonPrintPreview_Print;
            this.bbiPrint.Id = 4;
            this.bbiPrint.LargeGlyph = PrintRibbonControllerResources.RibbonPrintPreview_PrintLarge;
            this.bbiPrint.Name = "bbiPrint";
            tip5.FixedTooltipWidth = true;
            item9.Text = "In (Ctrl+P)";
            item10.LeftIndent = 6;
            item10.Text = "Chọn 1 m\x00e1y in, nhập v\x00e0o số bảng v\x00e0 c\x00e1c t\x00f9y chọn kh\x00e1c trước khi in.";
            tip5.Items.Add(item9);
            tip5.Items.Add(item10);
            tip5.MaxWidth = 210;
            this.bbiPrint.SuperTip = tip5;
            this.bbiQuickPrint.Caption = "In Nhanh";
            this.bbiQuickPrint.Command = PrintingSystemCommand.PrintDirect;
            this.bbiQuickPrint.ContextSpecifier = this.printRibbonController1;
            this.bbiQuickPrint.Enabled = false;
            this.bbiQuickPrint.Glyph = PrintRibbonControllerResources.RibbonPrintPreview_PrintDirect;
            this.bbiQuickPrint.Id = 5;
            this.bbiQuickPrint.LargeGlyph = PrintRibbonControllerResources.RibbonPrintPreview_PrintDirectLarge;
            this.bbiQuickPrint.Name = "bbiQuickPrint";
            tip6.FixedTooltipWidth = true;
            item11.Text = "In nhanh";
            item12.LeftIndent = 6;
            item12.Text = "In với 1 m\x00e1y in mặc định m\x00e0 kh\x00f4ng c\x00f3 bất cứ t\x00f9y chọn n\x00e0o.";
            tip6.Items.Add(item11);
            tip6.Items.Add(item12);
            tip6.MaxWidth = 210;
            this.bbiQuickPrint.SuperTip = tip6;
            this.printPreviewBarItem7.ButtonStyle = BarButtonStyle.Check;
            this.printPreviewBarItem7.Caption = "Custom Margins...";
            this.printPreviewBarItem7.Command = PrintingSystemCommand.PageSetup;
            this.printPreviewBarItem7.ContextSpecifier = this.printRibbonController1;
            this.printPreviewBarItem7.Enabled = false;
            this.printPreviewBarItem7.Id = 6;
            this.printPreviewBarItem7.Name = "printPreviewBarItem7";
            tip7.FixedTooltipWidth = true;
            item13.Text = "Page Setup";
            item14.LeftIndent = 6;
            item14.Text = "Show the Page Setup dialog.";
            tip7.Items.Add(item13);
            tip7.Items.Add(item14);
            tip7.MaxWidth = 210;
            this.printPreviewBarItem7.SuperTip = tip7;
            this.bbiHeaderFooter.Caption = "Đầu Trang/Cuối Trang";
            this.bbiHeaderFooter.Command = PrintingSystemCommand.EditPageHF;
            this.bbiHeaderFooter.ContextSpecifier = this.printRibbonController1;
            this.bbiHeaderFooter.Enabled = false;
            this.bbiHeaderFooter.Glyph = PrintRibbonControllerResources.RibbonPrintPreview_EditPageHF;
            this.bbiHeaderFooter.Id = 7;
            this.bbiHeaderFooter.LargeGlyph = PrintRibbonControllerResources.RibbonPrintPreview_EditPageHFLarge;
            this.bbiHeaderFooter.Name = "bbiHeaderFooter";
            tip8.FixedTooltipWidth = true;
            item15.Text = "Đầu trang v\x00e0 cuối trang";
            item16.LeftIndent = 6;
            item16.Text = "Chỉnh sửa nội dung hiển thị ở đầu trang v\x00e0 cuối trang in.";
            tip8.Items.Add(item15);
            tip8.Items.Add(item16);
            tip8.MaxWidth = 210;
            this.bbiHeaderFooter.SuperTip = tip8;
            this.bbiScale.ButtonStyle = BarButtonStyle.DropDown;
            this.bbiScale.Caption = "Co D\x00e3n";
            this.bbiScale.Command = PrintingSystemCommand.Scale;
            this.bbiScale.ContextSpecifier = this.printRibbonController1;
            this.bbiScale.Enabled = false;
            this.bbiScale.Glyph = PrintRibbonControllerResources.RibbonPrintPreview_Scale;
            this.bbiScale.Id = 8;
            this.bbiScale.LargeGlyph = PrintRibbonControllerResources.RibbonPrintPreview_ScaleLarge;
            this.bbiScale.Name = "bbiScale";
            tip9.FixedTooltipWidth = true;
            item17.Text = "Co D\x00e3n";
            item18.LeftIndent = 6;
            item18.Text = "Stretch or shrink the printed output to a percentage of its actual size.";
            tip9.Items.Add(item17);
            tip9.Items.Add(item18);
            tip9.MaxWidth = 210;
            this.bbiScale.SuperTip = tip9;
            this.bbiPointer.ButtonStyle = BarButtonStyle.Check;
            this.bbiPointer.Caption = "Pointer";
            this.bbiPointer.Command = PrintingSystemCommand.Pointer;
            this.bbiPointer.ContextSpecifier = this.printRibbonController1;
            this.bbiPointer.Down = true;
            this.bbiPointer.Enabled = false;
            this.bbiPointer.Glyph = PrintRibbonControllerResources.RibbonPrintPreview_Pointer;
            this.bbiPointer.GroupIndex = 1;
            this.bbiPointer.Id = 9;
            this.bbiPointer.Name = "bbiPointer";
            this.bbiPointer.RibbonStyle = RibbonItemStyles.SmallWithoutText;
            tip10.FixedTooltipWidth = true;
            item19.Text = "Mouse Pointer";
            item20.LeftIndent = 6;
            item20.Text = "Show the mouse pointer.";
            tip10.Items.Add(item19);
            tip10.Items.Add(item20);
            tip10.MaxWidth = 210;
            this.bbiPointer.SuperTip = tip10;
            this.bbiHandTool.ButtonStyle = BarButtonStyle.Check;
            this.bbiHandTool.Caption = "Hand Tool";
            this.bbiHandTool.Command = PrintingSystemCommand.HandTool;
            this.bbiHandTool.ContextSpecifier = this.printRibbonController1;
            this.bbiHandTool.Enabled = false;
            this.bbiHandTool.Glyph = PrintRibbonControllerResources.RibbonPrintPreview_HandTool;
            this.bbiHandTool.GroupIndex = 1;
            this.bbiHandTool.Id = 10;
            this.bbiHandTool.Name = "bbiHandTool";
            this.bbiHandTool.RibbonStyle = RibbonItemStyles.SmallWithoutText;
            tip11.FixedTooltipWidth = true;
            item21.Text = "Hand Tool";
            item22.LeftIndent = 6;
            item22.Text = "Invoke the Hand tool to manually scroll through pages.";
            tip11.Items.Add(item21);
            tip11.Items.Add(item22);
            tip11.MaxWidth = 210;
            this.bbiHandTool.SuperTip = tip11;
            this.bbiMagnifier.ButtonStyle = BarButtonStyle.Check;
            this.bbiMagnifier.Caption = "Magnifier";
            this.bbiMagnifier.Command = PrintingSystemCommand.Magnifier;
            this.bbiMagnifier.ContextSpecifier = this.printRibbonController1;
            this.bbiMagnifier.Enabled = false;
            this.bbiMagnifier.Glyph = PrintRibbonControllerResources.RibbonPrintPreview_Magnifier;
            this.bbiMagnifier.GroupIndex = 1;
            this.bbiMagnifier.Id = 11;
            this.bbiMagnifier.Name = "bbiMagnifier";
            this.bbiMagnifier.RibbonStyle = RibbonItemStyles.SmallWithoutText;
            tip12.FixedTooltipWidth = true;
            item23.Text = "Magnifier";
            item24.LeftIndent = 6;
            item24.Text = "Invoke the Magnifier tool.\r\n\r\nClicking once on a document zooms it so that a single page becomes entirely visible, while clicking another time zooms it to 100% of the normal size.";
            tip12.Items.Add(item23);
            tip12.Items.Add(item24);
            tip12.MaxWidth = 210;
            this.bbiMagnifier.SuperTip = tip12;
            this.bbiZoomOut.Caption = "Thu Nhỏ";
            this.bbiZoomOut.Command = PrintingSystemCommand.ZoomOut;
            this.bbiZoomOut.ContextSpecifier = this.printRibbonController1;
            this.bbiZoomOut.Enabled = false;
            this.bbiZoomOut.Glyph = PrintRibbonControllerResources.RibbonPrintPreview_ZoomOut;
            this.bbiZoomOut.Id = 12;
            this.bbiZoomOut.LargeGlyph = PrintRibbonControllerResources.RibbonPrintPreview_ZoomOutLarge;
            this.bbiZoomOut.Name = "bbiZoomOut";
            tip13.FixedTooltipWidth = true;
            item25.Text = "Thu nhỏ";
            item26.LeftIndent = 6;
            item26.Text = "Zoom out to see more of the page at a reduced size.";
            tip13.Items.Add(item25);
            tip13.Items.Add(item26);
            tip13.MaxWidth = 210;
            this.bbiZoomOut.SuperTip = tip13;
            this.bbiZoomIn.Caption = "Ph\x00f3ng To";
            this.bbiZoomIn.Command = PrintingSystemCommand.ZoomIn;
            this.bbiZoomIn.ContextSpecifier = this.printRibbonController1;
            this.bbiZoomIn.Enabled = false;
            this.bbiZoomIn.Glyph = PrintRibbonControllerResources.RibbonPrintPreview_ZoomIn;
            this.bbiZoomIn.Id = 13;
            this.bbiZoomIn.LargeGlyph = PrintRibbonControllerResources.RibbonPrintPreview_ZoomInLarge;
            this.bbiZoomIn.Name = "bbiZoomIn";
            tip14.FixedTooltipWidth = true;
            item27.Text = "Ph\x00f3ng to";
            item28.LeftIndent = 6;
            item28.Text = "Zoom in to get a close-up view of the document.";
            tip14.Items.Add(item27);
            tip14.Items.Add(item28);
            tip14.MaxWidth = 210;
            this.bbiZoomIn.SuperTip = tip14;
            this.bbiZoom.ButtonStyle = BarButtonStyle.DropDown;
            this.bbiZoom.Caption = "Độ Lớn";
            this.bbiZoom.Command = PrintingSystemCommand.Zoom;
            this.bbiZoom.ContextSpecifier = this.printRibbonController1;
            this.bbiZoom.Enabled = false;
            this.bbiZoom.Glyph = PrintRibbonControllerResources.RibbonPrintPreview_Zoom;
            this.bbiZoom.Id = 14;
            this.bbiZoom.LargeGlyph = PrintRibbonControllerResources.RibbonPrintPreview_ZoomLarge;
            this.bbiZoom.Name = "bbiZoom";
            tip15.FixedTooltipWidth = true;
            item29.Text = "Độ thu/ph\x00f3ng";
            item30.LeftIndent = 6;
            item30.Text = "Change the zoom level of the document preview.";
            tip15.Items.Add(item29);
            tip15.Items.Add(item30);
            tip15.MaxWidth = 210;
            this.bbiZoom.SuperTip = tip15;
            this.bbiFirstPage.Caption = "Trang Đầu";
            this.bbiFirstPage.Command = PrintingSystemCommand.ShowFirstPage;
            this.bbiFirstPage.ContextSpecifier = this.printRibbonController1;
            this.bbiFirstPage.Enabled = false;
            this.bbiFirstPage.Glyph = PrintRibbonControllerResources.RibbonPrintPreview_ShowFirstPage;
            this.bbiFirstPage.Id = 15;
            this.bbiFirstPage.LargeGlyph = PrintRibbonControllerResources.RibbonPrintPreview_ShowFirstPageLarge;
            this.bbiFirstPage.Name = "bbiFirstPage";
            tip16.FixedTooltipWidth = true;
            item31.Text = "Trang đầu ti\x00ean (Ctrl+Home)";
            item32.LeftIndent = 6;
            item32.Text = "Navigate to the first page of the document.";
            tip16.Items.Add(item31);
            tip16.Items.Add(item32);
            tip16.MaxWidth = 210;
            this.bbiFirstPage.SuperTip = tip16;
            this.bbiPreviousPage.Caption = "Trang Trước";
            this.bbiPreviousPage.Command = PrintingSystemCommand.ShowPrevPage;
            this.bbiPreviousPage.ContextSpecifier = this.printRibbonController1;
            this.bbiPreviousPage.Enabled = false;
            this.bbiPreviousPage.Glyph = PrintRibbonControllerResources.RibbonPrintPreview_ShowPrevPage;
            this.bbiPreviousPage.Id = 0x10;
            this.bbiPreviousPage.LargeGlyph = PrintRibbonControllerResources.RibbonPrintPreview_ShowPrevPageLarge;
            this.bbiPreviousPage.Name = "bbiPreviousPage";
            tip17.FixedTooltipWidth = true;
            item33.Text = "Trang trước (PageUp)";
            item34.LeftIndent = 6;
            item34.Text = "Navigate to the previous page of the document.";
            tip17.Items.Add(item33);
            tip17.Items.Add(item34);
            tip17.MaxWidth = 210;
            this.bbiPreviousPage.SuperTip = tip17;
            this.bbiNextPage.Caption = "Trang Tiếp";
            this.bbiNextPage.Command = PrintingSystemCommand.ShowNextPage;
            this.bbiNextPage.ContextSpecifier = this.printRibbonController1;
            this.bbiNextPage.Enabled = false;
            this.bbiNextPage.Glyph = PrintRibbonControllerResources.RibbonPrintPreview_ShowNextPage;
            this.bbiNextPage.Id = 0x11;
            this.bbiNextPage.LargeGlyph = PrintRibbonControllerResources.RibbonPrintPreview_ShowNextPageLarge;
            this.bbiNextPage.Name = "bbiNextPage";
            tip18.FixedTooltipWidth = true;
            item35.Text = "Trang tiếp theo (PageDown)";
            item36.LeftIndent = 6;
            item36.Text = "Navigate to the next page of the document.";
            tip18.Items.Add(item35);
            tip18.Items.Add(item36);
            tip18.MaxWidth = 210;
            this.bbiNextPage.SuperTip = tip18;
            this.bbiLastPage.Caption = "Trang Cuối";
            this.bbiLastPage.Command = PrintingSystemCommand.ShowLastPage;
            this.bbiLastPage.ContextSpecifier = this.printRibbonController1;
            this.bbiLastPage.Enabled = false;
            this.bbiLastPage.Glyph = PrintRibbonControllerResources.RibbonPrintPreview_ShowLastPage;
            this.bbiLastPage.Id = 0x12;
            this.bbiLastPage.LargeGlyph = PrintRibbonControllerResources.RibbonPrintPreview_ShowLastPageLarge;
            this.bbiLastPage.Name = "bbiLastPage";
            tip19.FixedTooltipWidth = true;
            item37.Text = "Trang cuối c\x00f9ng (Ctrl+End)";
            item38.LeftIndent = 6;
            item38.Text = "Navigate to the last page of the document.";
            tip19.Items.Add(item37);
            tip19.Items.Add(item38);
            tip19.MaxWidth = 210;
            this.bbiLastPage.SuperTip = tip19;
            this.bbiManyPages.ButtonStyle = BarButtonStyle.DropDown;
            this.bbiManyPages.Caption = "Nhiều Trang";
            this.bbiManyPages.Command = PrintingSystemCommand.MultiplePages;
            this.bbiManyPages.ContextSpecifier = this.printRibbonController1;
            this.bbiManyPages.Enabled = false;
            this.bbiManyPages.Glyph = PrintRibbonControllerResources.RibbonPrintPreview_MultiplePages;
            this.bbiManyPages.Id = 0x13;
            this.bbiManyPages.LargeGlyph = PrintRibbonControllerResources.RibbonPrintPreview_MultiplePagesLarge;
            this.bbiManyPages.Name = "bbiManyPages";
            tip20.FixedTooltipWidth = true;
            item39.Text = "Xem nhiều trang";
            item40.LeftIndent = 6;
            item40.Text = "Choose the page layout to arrange the document pages in preview.";
            tip20.Items.Add(item39);
            tip20.Items.Add(item40);
            tip20.MaxWidth = 210;
            this.bbiManyPages.SuperTip = tip20;
            this.bbiPageColor.ButtonStyle = BarButtonStyle.DropDown;
            this.bbiPageColor.Caption = "M\x00e0u Nền";
            this.bbiPageColor.Command = PrintingSystemCommand.FillBackground;
            this.bbiPageColor.ContextSpecifier = this.printRibbonController1;
            this.bbiPageColor.Enabled = false;
            this.bbiPageColor.Glyph = PrintRibbonControllerResources.RibbonPrintPreview_FillBackground;
            this.bbiPageColor.Id = 20;
            this.bbiPageColor.LargeGlyph = PrintRibbonControllerResources.RibbonPrintPreview_FillBackgroundLarge;
            this.bbiPageColor.Name = "bbiPageColor";
            tip21.FixedTooltipWidth = true;
            item41.Text = "M\x00e0u nền trang in";
            item42.LeftIndent = 6;
            item42.Text = "Choose a color for the background of the document pages.";
            tip21.Items.Add(item41);
            tip21.Items.Add(item42);
            tip21.MaxWidth = 210;
            this.bbiPageColor.SuperTip = tip21;
            this.bbiWatermark.Caption = "Chữ Mờ";
            this.bbiWatermark.Command = PrintingSystemCommand.Watermark;
            this.bbiWatermark.ContextSpecifier = this.printRibbonController1;
            this.bbiWatermark.Enabled = false;
            this.bbiWatermark.Glyph = PrintRibbonControllerResources.RibbonPrintPreview_Watermark;
            this.bbiWatermark.Id = 0x15;
            this.bbiWatermark.LargeGlyph = PrintRibbonControllerResources.RibbonPrintPreview_WatermarkLarge;
            this.bbiWatermark.Name = "bbiWatermark";
            tip22.FixedTooltipWidth = true;
            item43.Text = "Chữ mờ";
            item44.LeftIndent = 6;
            item44.Text = "Insert ghosted text or image behind the content of a page.\r\n\r\nThis is often used to indicate that a document is to be treated specially.";
            tip22.Items.Add(item43);
            tip22.Items.Add(item44);
            tip22.MaxWidth = 210;
            this.bbiWatermark.SuperTip = tip22;
            this.bbiExportTo.ButtonStyle = BarButtonStyle.DropDown;
            this.bbiExportTo.Caption = "Xuất ra...";
            this.bbiExportTo.Command = PrintingSystemCommand.ExportFile;
            this.bbiExportTo.ContextSpecifier = this.printRibbonController1;
            this.bbiExportTo.Enabled = false;
            this.bbiExportTo.Glyph = (Image) manager.GetObject("bbiExportTo.Glyph");
            this.bbiExportTo.Id = 0x16;
            this.bbiExportTo.LargeGlyph = (Image) manager.GetObject("bbiExportTo.LargeGlyph");
            this.bbiExportTo.Name = "bbiExportTo";
            tip23.FixedTooltipWidth = true;
            item45.Text = "Xuất ra...";
            item46.LeftIndent = 6;
            item46.Text = "Export the current document in one of the available formats, and save it to the file on a disk.";
            tip23.Items.Add(item45);
            tip23.Items.Add(item46);
            tip23.MaxWidth = 210;
            this.bbiExportTo.SuperTip = tip23;
            this.bbiEmailAs.ButtonStyle = BarButtonStyle.DropDown;
            this.bbiEmailAs.Caption = "E-Mail As";
            this.bbiEmailAs.Command = PrintingSystemCommand.SendFile;
            this.bbiEmailAs.ContextSpecifier = this.printRibbonController1;
            this.bbiEmailAs.Enabled = false;
            this.bbiEmailAs.Glyph = (Image) manager.GetObject("bbiEmailAs.Glyph");
            this.bbiEmailAs.Id = 0x17;
            this.bbiEmailAs.LargeGlyph = (Image) manager.GetObject("bbiEmailAs.LargeGlyph");
            this.bbiEmailAs.Name = "bbiEmailAs";
            tip24.FixedTooltipWidth = true;
            item47.Text = "E-Mail As...";
            item48.LeftIndent = 6;
            item48.Text = "Export the current document in one of the available formats, and attach it to the e-mail.";
            tip24.Items.Add(item47);
            tip24.Items.Add(item48);
            tip24.MaxWidth = 210;
            this.bbiEmailAs.SuperTip = tip24;
            this.bbiClosePrintPreview.Caption = "Đ\x00f3ng";
            this.bbiClosePrintPreview.Command = PrintingSystemCommand.ClosePreview;
            this.bbiClosePrintPreview.ContextSpecifier = this.printRibbonController1;
            this.bbiClosePrintPreview.Enabled = false;
            this.bbiClosePrintPreview.Glyph = PrintRibbonControllerResources.RibbonPrintPreview_ClosePreview;
            this.bbiClosePrintPreview.Id = 0x18;
            this.bbiClosePrintPreview.LargeGlyph = PrintRibbonControllerResources.RibbonPrintPreview_ClosePreviewLarge;
            this.bbiClosePrintPreview.Name = "bbiClosePrintPreview";
            tip25.FixedTooltipWidth = true;
            item49.Text = "Đ\x00f3ng";
            item50.LeftIndent = 6;
            item50.Text = "Đ\x00f3ng trang xem b\x00e1o c\x00e1o.";
            tip25.Items.Add(item49);
            tip25.Items.Add(item50);
            tip25.MaxWidth = 210;
            this.bbiClosePrintPreview.SuperTip = tip25;
            this.bbiOrientation.ButtonStyle = BarButtonStyle.DropDown;
            this.bbiOrientation.Caption = "Xoay";
            this.bbiOrientation.Command = PrintingSystemCommand.PageOrientation;
            this.bbiOrientation.ContextSpecifier = this.printRibbonController1;
            this.bbiOrientation.Enabled = false;
            this.bbiOrientation.Glyph = PrintRibbonControllerResources.RibbonPrintPreview_PageOrientation;
            this.bbiOrientation.Id = 0x19;
            this.bbiOrientation.LargeGlyph = PrintRibbonControllerResources.RibbonPrintPreview_PageOrientationLarge;
            this.bbiOrientation.Name = "bbiOrientation";
            tip26.FixedTooltipWidth = true;
            item51.Text = "Xoay trang";
            item52.LeftIndent = 6;
            item52.Text = "Switch the pages between portrait and landscape layouts.";
            tip26.Items.Add(item51);
            tip26.Items.Add(item52);
            tip26.MaxWidth = 210;
            this.bbiOrientation.SuperTip = tip26;
            this.bbiSize.ButtonStyle = BarButtonStyle.DropDown;
            this.bbiSize.Caption = "K\x00edch Thước";
            this.bbiSize.Command = PrintingSystemCommand.PaperSize;
            this.bbiSize.ContextSpecifier = this.printRibbonController1;
            this.bbiSize.Enabled = false;
            this.bbiSize.Glyph = PrintRibbonControllerResources.RibbonPrintPreview_PaperSize;
            this.bbiSize.Id = 0x1a;
            this.bbiSize.LargeGlyph = PrintRibbonControllerResources.RibbonPrintPreview_PaperSizeLarge;
            this.bbiSize.Name = "bbiSize";
            tip27.FixedTooltipWidth = true;
            item53.Text = "Khổ giấy";
            item54.LeftIndent = 6;
            item54.Text = "Lựa chọn k\x00edch thước khổ giấy cho t\x00e0i liệu in";
            tip27.Items.Add(item53);
            tip27.Items.Add(item54);
            tip27.MaxWidth = 210;
            this.bbiSize.SuperTip = tip27;
            this.bbiMargins.ButtonStyle = BarButtonStyle.DropDown;
            this.bbiMargins.Caption = "Canh Lề";
            this.bbiMargins.Command = PrintingSystemCommand.PageMargins;
            this.bbiMargins.ContextSpecifier = this.printRibbonController1;
            this.bbiMargins.Enabled = false;
            this.bbiMargins.Glyph = PrintRibbonControllerResources.RibbonPrintPreview_PageMargins;
            this.bbiMargins.Id = 0x1b;
            this.bbiMargins.LargeGlyph = PrintRibbonControllerResources.RibbonPrintPreview_PageMarginsLarge;
            this.bbiMargins.Name = "bbiMargins";
            tip28.FixedTooltipWidth = true;
            item55.Text = "Canh lề trang in";
            item56.LeftIndent = 6;
            item56.Text = "Select the margin sizes for the entire document.\r\n\r\nTo apply specific margin sizes to the document, click Custom Margins.";
            tip28.Items.Add(item55);
            tip28.Items.Add(item56);
            tip28.MaxWidth = 210;
            this.bbiMargins.SuperTip = tip28;
            this.printPreviewBarItem29.Caption = "Tập tin PDF";
            this.printPreviewBarItem29.Command = PrintingSystemCommand.SendPdf;
            this.printPreviewBarItem29.ContextSpecifier = this.printRibbonController1;
            this.printPreviewBarItem29.Description = "Adobe Portable Document Format";
            this.printPreviewBarItem29.Enabled = false;
            this.printPreviewBarItem29.Glyph = PrintRibbonControllerResources.RibbonPrintPreview_SendPdf;
            this.printPreviewBarItem29.Id = 0x1c;
            this.printPreviewBarItem29.LargeGlyph = PrintRibbonControllerResources.RibbonPrintPreview_SendPdfLarge;
            this.printPreviewBarItem29.Name = "printPreviewBarItem29";
            tip29.FixedTooltipWidth = true;
            item57.Text = "E-Mail As PDF";
            item58.LeftIndent = 6;
            item58.Text = "Export the document to PDF and attach it to the e-mail.";
            tip29.Items.Add(item57);
            tip29.Items.Add(item58);
            tip29.MaxWidth = 210;
            this.printPreviewBarItem29.SuperTip = tip29;
            this.printPreviewBarItem30.Caption = "Tập tin TXT";
            this.printPreviewBarItem30.Command = PrintingSystemCommand.SendTxt;
            this.printPreviewBarItem30.ContextSpecifier = this.printRibbonController1;
            this.printPreviewBarItem30.Description = "Plain Text";
            this.printPreviewBarItem30.Enabled = false;
            this.printPreviewBarItem30.Glyph = PrintRibbonControllerResources.RibbonPrintPreview_SendTxt;
            this.printPreviewBarItem30.Id = 0x1d;
            this.printPreviewBarItem30.LargeGlyph = PrintRibbonControllerResources.RibbonPrintPreview_SendTxtLarge;
            this.printPreviewBarItem30.Name = "printPreviewBarItem30";
            tip30.FixedTooltipWidth = true;
            item59.Text = "E-Mail As Text";
            item60.LeftIndent = 6;
            item60.Text = "Export the document to Text and attach it to the e-mail.";
            tip30.Items.Add(item59);
            tip30.Items.Add(item60);
            tip30.MaxWidth = 210;
            this.printPreviewBarItem30.SuperTip = tip30;
            this.printPreviewBarItem31.Caption = "Tập tin CSV";
            this.printPreviewBarItem31.Command = PrintingSystemCommand.SendCsv;
            this.printPreviewBarItem31.ContextSpecifier = this.printRibbonController1;
            this.printPreviewBarItem31.Description = "Comma-Separated Values Text";
            this.printPreviewBarItem31.Enabled = false;
            this.printPreviewBarItem31.Glyph = PrintRibbonControllerResources.RibbonPrintPreview_SendCsv;
            this.printPreviewBarItem31.Id = 30;
            this.printPreviewBarItem31.LargeGlyph = PrintRibbonControllerResources.RibbonPrintPreview_SendCsvLarge;
            this.printPreviewBarItem31.Name = "printPreviewBarItem31";
            tip31.FixedTooltipWidth = true;
            item61.Text = "E-Mail As CSV";
            item62.LeftIndent = 6;
            item62.Text = "Export the document to CSV and attach it to the e-mail.";
            tip31.Items.Add(item61);
            tip31.Items.Add(item62);
            tip31.MaxWidth = 210;
            this.printPreviewBarItem31.SuperTip = tip31;
            this.printPreviewBarItem32.Caption = "Tập tin MHT";
            this.printPreviewBarItem32.Command = PrintingSystemCommand.SendMht;
            this.printPreviewBarItem32.ContextSpecifier = this.printRibbonController1;
            this.printPreviewBarItem32.Description = "Single File Web Page";
            this.printPreviewBarItem32.Enabled = false;
            this.printPreviewBarItem32.Glyph = PrintRibbonControllerResources.RibbonPrintPreview_SendMht;
            this.printPreviewBarItem32.Id = 0x1f;
            this.printPreviewBarItem32.LargeGlyph = PrintRibbonControllerResources.RibbonPrintPreview_SendMhtLarge;
            this.printPreviewBarItem32.Name = "printPreviewBarItem32";
            tip32.FixedTooltipWidth = true;
            item63.Text = "E-Mail As MHT";
            item64.LeftIndent = 6;
            item64.Text = "Export the document to MHT and attach it to the e-mail.";
            tip32.Items.Add(item63);
            tip32.Items.Add(item64);
            tip32.MaxWidth = 210;
            this.printPreviewBarItem32.SuperTip = tip32;
            this.printPreviewBarItem33.Caption = "Tập tin XLS";
            this.printPreviewBarItem33.Command = PrintingSystemCommand.SendXls;
            this.printPreviewBarItem33.ContextSpecifier = this.printRibbonController1;
            this.printPreviewBarItem33.Description = "Microsoft Excel 2000-2003 Workbook";
            this.printPreviewBarItem33.Enabled = false;
            this.printPreviewBarItem33.Glyph = PrintRibbonControllerResources.RibbonPrintPreview_SendXls;
            this.printPreviewBarItem33.Id = 0x20;
            this.printPreviewBarItem33.LargeGlyph = PrintRibbonControllerResources.RibbonPrintPreview_SendXlsLarge;
            this.printPreviewBarItem33.Name = "printPreviewBarItem33";
            tip33.FixedTooltipWidth = true;
            item65.Text = "E-Mail As XLS";
            item66.LeftIndent = 6;
            item66.Text = "Export the document to XLS and attach it to the e-mail.";
            tip33.Items.Add(item65);
            tip33.Items.Add(item66);
            tip33.MaxWidth = 210;
            this.printPreviewBarItem33.SuperTip = tip33;
            this.printPreviewBarItem34.Caption = "Tập tin XLSX";
            this.printPreviewBarItem34.Command = PrintingSystemCommand.SendXlsx;
            this.printPreviewBarItem34.ContextSpecifier = this.printRibbonController1;
            this.printPreviewBarItem34.Description = "Microsoft Excel 2007 Workbook";
            this.printPreviewBarItem34.Enabled = false;
            this.printPreviewBarItem34.Glyph = PrintRibbonControllerResources.RibbonPrintPreview_SendXlsx;
            this.printPreviewBarItem34.Id = 0x21;
            this.printPreviewBarItem34.LargeGlyph = PrintRibbonControllerResources.RibbonPrintPreview_SendXlsxLarge;
            this.printPreviewBarItem34.Name = "printPreviewBarItem34";
            tip34.FixedTooltipWidth = true;
            item67.Text = "E-Mail As XLSX";
            item68.LeftIndent = 6;
            item68.Text = "Export the document to XLSX and attach it to the e-mail.";
            tip34.Items.Add(item67);
            tip34.Items.Add(item68);
            tip34.MaxWidth = 210;
            this.printPreviewBarItem34.SuperTip = tip34;
            this.printPreviewBarItem35.Caption = "Tập tin RTF";
            this.printPreviewBarItem35.Command = PrintingSystemCommand.SendRtf;
            this.printPreviewBarItem35.ContextSpecifier = this.printRibbonController1;
            this.printPreviewBarItem35.Description = "Rich Text Format";
            this.printPreviewBarItem35.Enabled = false;
            this.printPreviewBarItem35.Glyph = PrintRibbonControllerResources.RibbonPrintPreview_SendRtf;
            this.printPreviewBarItem35.Id = 0x22;
            this.printPreviewBarItem35.LargeGlyph = PrintRibbonControllerResources.RibbonPrintPreview_SendRtfLarge;
            this.printPreviewBarItem35.Name = "printPreviewBarItem35";
            tip35.FixedTooltipWidth = true;
            item69.Text = "E-Mail As RTF";
            item70.LeftIndent = 6;
            item70.Text = "Export the document to RTF and attach it to the e-mail.";
            tip35.Items.Add(item69);
            tip35.Items.Add(item70);
            tip35.MaxWidth = 210;
            this.printPreviewBarItem35.SuperTip = tip35;
            this.printPreviewBarItem36.Caption = "Tập tin h\x00ecnh ảnh";
            this.printPreviewBarItem36.Command = PrintingSystemCommand.SendGraphic;
            this.printPreviewBarItem36.ContextSpecifier = this.printRibbonController1;
            this.printPreviewBarItem36.Description = "BMP, GIF, JPEG, PNG, TIFF, EMF, WMF";
            this.printPreviewBarItem36.Enabled = false;
            this.printPreviewBarItem36.Glyph = PrintRibbonControllerResources.RibbonPrintPreview_SendGraphic;
            this.printPreviewBarItem36.Id = 0x23;
            this.printPreviewBarItem36.LargeGlyph = PrintRibbonControllerResources.RibbonPrintPreview_SendGraphicLarge;
            this.printPreviewBarItem36.Name = "printPreviewBarItem36";
            tip36.FixedTooltipWidth = true;
            item71.Text = "E-Mail As Image";
            item72.LeftIndent = 6;
            item72.Text = "Export the document to Image and attach it to the e-mail.";
            tip36.Items.Add(item71);
            tip36.Items.Add(item72);
            tip36.MaxWidth = 210;
            this.printPreviewBarItem36.SuperTip = tip36;
            this.printPreviewBarItem37.Caption = "Tập tin PDF";
            this.printPreviewBarItem37.Command = PrintingSystemCommand.ExportPdf;
            this.printPreviewBarItem37.ContextSpecifier = this.printRibbonController1;
            this.printPreviewBarItem37.Description = "Adobe Portable Document Format";
            this.printPreviewBarItem37.Enabled = false;
            this.printPreviewBarItem37.Glyph = PrintRibbonControllerResources.RibbonPrintPreview_ExportPdf;
            this.printPreviewBarItem37.Id = 0x24;
            this.printPreviewBarItem37.LargeGlyph = PrintRibbonControllerResources.RibbonPrintPreview_ExportPdfLarge;
            this.printPreviewBarItem37.Name = "printPreviewBarItem37";
            tip37.FixedTooltipWidth = true;
            item73.Text = "Export to PDF";
            item74.LeftIndent = 6;
            item74.Text = "Export the document to PDF and save it to the file on a disk.";
            tip37.Items.Add(item73);
            tip37.Items.Add(item74);
            tip37.MaxWidth = 210;
            this.printPreviewBarItem37.SuperTip = tip37;
            this.printPreviewBarItem38.Caption = "Tập tin HTML";
            this.printPreviewBarItem38.Command = PrintingSystemCommand.ExportHtm;
            this.printPreviewBarItem38.ContextSpecifier = this.printRibbonController1;
            this.printPreviewBarItem38.Description = "Web Page";
            this.printPreviewBarItem38.Enabled = false;
            this.printPreviewBarItem38.Glyph = PrintRibbonControllerResources.RibbonPrintPreview_ExportHtm;
            this.printPreviewBarItem38.Id = 0x25;
            this.printPreviewBarItem38.LargeGlyph = PrintRibbonControllerResources.RibbonPrintPreview_ExportHtmLarge;
            this.printPreviewBarItem38.Name = "printPreviewBarItem38";
            tip38.FixedTooltipWidth = true;
            item75.Text = "Export to HTML";
            item76.LeftIndent = 6;
            item76.Text = "Export the document to HTML and save it to the file on a disk.";
            tip38.Items.Add(item75);
            tip38.Items.Add(item76);
            tip38.MaxWidth = 210;
            this.printPreviewBarItem38.SuperTip = tip38;
            this.printPreviewBarItem39.Caption = "Tập tin TXT";
            this.printPreviewBarItem39.Command = PrintingSystemCommand.ExportTxt;
            this.printPreviewBarItem39.ContextSpecifier = this.printRibbonController1;
            this.printPreviewBarItem39.Description = "Plain Text";
            this.printPreviewBarItem39.Enabled = false;
            this.printPreviewBarItem39.Glyph = PrintRibbonControllerResources.RibbonPrintPreview_ExportTxt;
            this.printPreviewBarItem39.Id = 0x26;
            this.printPreviewBarItem39.LargeGlyph = PrintRibbonControllerResources.RibbonPrintPreview_ExportTxtLarge;
            this.printPreviewBarItem39.Name = "printPreviewBarItem39";
            tip39.FixedTooltipWidth = true;
            item77.Text = "Export to Text";
            item78.LeftIndent = 6;
            item78.Text = "Export the document to Text and save it to the file on a disk.";
            tip39.Items.Add(item77);
            tip39.Items.Add(item78);
            tip39.MaxWidth = 210;
            this.printPreviewBarItem39.SuperTip = tip39;
            this.printPreviewBarItem40.Caption = "Tập tin CSV";
            this.printPreviewBarItem40.Command = PrintingSystemCommand.ExportCsv;
            this.printPreviewBarItem40.ContextSpecifier = this.printRibbonController1;
            this.printPreviewBarItem40.Description = "Comma-Separated Values Text";
            this.printPreviewBarItem40.Enabled = false;
            this.printPreviewBarItem40.Glyph = PrintRibbonControllerResources.RibbonPrintPreview_ExportCsv;
            this.printPreviewBarItem40.Id = 0x27;
            this.printPreviewBarItem40.LargeGlyph = PrintRibbonControllerResources.RibbonPrintPreview_ExportCsvLarge;
            this.printPreviewBarItem40.Name = "printPreviewBarItem40";
            tip40.FixedTooltipWidth = true;
            item79.Text = "Export to CSV";
            item80.LeftIndent = 6;
            item80.Text = "Export the document to CSV and save it to the file on a disk.";
            tip40.Items.Add(item79);
            tip40.Items.Add(item80);
            tip40.MaxWidth = 210;
            this.printPreviewBarItem40.SuperTip = tip40;
            this.printPreviewBarItem41.Caption = "Tập tin MHT";
            this.printPreviewBarItem41.Command = PrintingSystemCommand.ExportMht;
            this.printPreviewBarItem41.ContextSpecifier = this.printRibbonController1;
            this.printPreviewBarItem41.Description = "Single File Web Page";
            this.printPreviewBarItem41.Enabled = false;
            this.printPreviewBarItem41.Glyph = PrintRibbonControllerResources.RibbonPrintPreview_ExportMht;
            this.printPreviewBarItem41.Id = 40;
            this.printPreviewBarItem41.LargeGlyph = PrintRibbonControllerResources.RibbonPrintPreview_ExportMhtLarge;
            this.printPreviewBarItem41.Name = "printPreviewBarItem41";
            tip41.FixedTooltipWidth = true;
            item81.Text = "Export to MHT";
            item82.LeftIndent = 6;
            item82.Text = "Export the document to MHT and save it to the file on a disk.";
            tip41.Items.Add(item81);
            tip41.Items.Add(item82);
            tip41.MaxWidth = 210;
            this.printPreviewBarItem41.SuperTip = tip41;
            this.printPreviewBarItem42.Caption = "Tập tin XLS";
            this.printPreviewBarItem42.Command = PrintingSystemCommand.ExportXls;
            this.printPreviewBarItem42.ContextSpecifier = this.printRibbonController1;
            this.printPreviewBarItem42.Description = "Microsoft Excel 2000-2003 Workbook";
            this.printPreviewBarItem42.Enabled = false;
            this.printPreviewBarItem42.Glyph = PrintRibbonControllerResources.RibbonPrintPreview_ExportXls;
            this.printPreviewBarItem42.Id = 0x29;
            this.printPreviewBarItem42.LargeGlyph = PrintRibbonControllerResources.RibbonPrintPreview_ExportXlsLarge;
            this.printPreviewBarItem42.Name = "printPreviewBarItem42";
            tip42.FixedTooltipWidth = true;
            item83.Text = "Export to XLS";
            item84.LeftIndent = 6;
            item84.Text = "Export the document to XLS and save it to the file on a disk.";
            tip42.Items.Add(item83);
            tip42.Items.Add(item84);
            tip42.MaxWidth = 210;
            this.printPreviewBarItem42.SuperTip = tip42;
            this.printPreviewBarItem43.Caption = "Tập tin XLSX";
            this.printPreviewBarItem43.Command = PrintingSystemCommand.ExportXlsx;
            this.printPreviewBarItem43.ContextSpecifier = this.printRibbonController1;
            this.printPreviewBarItem43.Description = "Microsoft Excel 2007 Workbook";
            this.printPreviewBarItem43.Enabled = false;
            this.printPreviewBarItem43.Glyph = PrintRibbonControllerResources.RibbonPrintPreview_ExportXlsx;
            this.printPreviewBarItem43.Id = 0x2a;
            this.printPreviewBarItem43.LargeGlyph = PrintRibbonControllerResources.RibbonPrintPreview_ExportXlsxLarge;
            this.printPreviewBarItem43.Name = "printPreviewBarItem43";
            tip43.FixedTooltipWidth = true;
            item85.Text = "Export to XLSX";
            item86.LeftIndent = 6;
            item86.Text = "Export the document to XLSX and save it to the file on a disk.";
            tip43.Items.Add(item85);
            tip43.Items.Add(item86);
            tip43.MaxWidth = 210;
            this.printPreviewBarItem43.SuperTip = tip43;
            this.printPreviewBarItem44.Caption = "Tập tin RTF";
            this.printPreviewBarItem44.Command = PrintingSystemCommand.ExportRtf;
            this.printPreviewBarItem44.ContextSpecifier = this.printRibbonController1;
            this.printPreviewBarItem44.Description = "Rich Text Format";
            this.printPreviewBarItem44.Enabled = false;
            this.printPreviewBarItem44.Glyph = PrintRibbonControllerResources.RibbonPrintPreview_ExportRtf;
            this.printPreviewBarItem44.Id = 0x2b;
            this.printPreviewBarItem44.LargeGlyph = PrintRibbonControllerResources.RibbonPrintPreview_ExportRtfLarge;
            this.printPreviewBarItem44.Name = "printPreviewBarItem44";
            tip44.FixedTooltipWidth = true;
            item87.Text = "Export to RTF";
            item88.LeftIndent = 6;
            item88.Text = "Export the document to RTF and save it to the file on a disk.";
            tip44.Items.Add(item87);
            tip44.Items.Add(item88);
            tip44.MaxWidth = 210;
            this.printPreviewBarItem44.SuperTip = tip44;
            this.printPreviewBarItem45.Caption = "Tập tin h\x00ecnh ảnh";
            this.printPreviewBarItem45.Command = PrintingSystemCommand.ExportGraphic;
            this.printPreviewBarItem45.ContextSpecifier = this.printRibbonController1;
            this.printPreviewBarItem45.Description = "BMP, GIF, JPEG, PNG, TIFF, EMF, WMF";
            this.printPreviewBarItem45.Enabled = false;
            this.printPreviewBarItem45.Glyph = PrintRibbonControllerResources.RibbonPrintPreview_ExportGraphic;
            this.printPreviewBarItem45.Id = 0x2c;
            this.printPreviewBarItem45.LargeGlyph = PrintRibbonControllerResources.RibbonPrintPreview_ExportGraphicLarge;
            this.printPreviewBarItem45.Name = "printPreviewBarItem45";
            tip45.FixedTooltipWidth = true;
            item89.Text = "Export to Image";
            item90.LeftIndent = 6;
            item90.Text = "Export the document to Image and save it to the file on a disk.";
            tip45.Items.Add(item89);
            tip45.Items.Add(item90);
            tip45.MaxWidth = 210;
            this.printPreviewBarItem45.SuperTip = tip45;
            this.bbiOpen.Caption = "Mở...";
            this.bbiOpen.Command = PrintingSystemCommand.Open;
            this.bbiOpen.ContextSpecifier = this.printRibbonController1;
            this.bbiOpen.Enabled = false;
            this.bbiOpen.Glyph = PrintRibbonControllerResources.RibbonPrintPreview_Open;
            this.bbiOpen.Id = 0x2d;
            this.bbiOpen.LargeGlyph = PrintRibbonControllerResources.RibbonPrintPreview_OpenLarge;
            this.bbiOpen.Name = "bbiOpen";
            tip46.FixedTooltipWidth = true;
            item91.Text = "Mở (Ctrl + O)";
            item92.LeftIndent = 6;
            item92.Text = "Mở 1 t\x00e0i liệu.";
            tip46.Items.Add(item91);
            tip46.Items.Add(item92);
            tip46.MaxWidth = 210;
            this.bbiOpen.SuperTip = tip46;
            this.bbiSave.Caption = "Lưu";
            this.bbiSave.Command = PrintingSystemCommand.Save;
            this.bbiSave.ContextSpecifier = this.printRibbonController1;
            this.bbiSave.Enabled = false;
            this.bbiSave.Glyph = PrintRibbonControllerResources.RibbonPrintPreview_Save;
            this.bbiSave.Id = 0x2e;
            this.bbiSave.LargeGlyph = PrintRibbonControllerResources.RibbonPrintPreview_SaveLarge;
            this.bbiSave.Name = "bbiSave";
            tip47.FixedTooltipWidth = true;
            item93.Text = "Lưu (Ctrl + S)";
            item94.LeftIndent = 6;
            item94.Text = "Lưu t\x00e0i liệu.";
            tip47.Items.Add(item93);
            tip47.Items.Add(item94);
            tip47.MaxWidth = 210;
            this.bbiSave.SuperTip = tip47;
            this.printPreviewStaticItem1.Caption = "Page 0 of 0";
            this.printPreviewStaticItem1.Id = 0x2f;
            this.printPreviewStaticItem1.LeftIndent = 1;
            this.printPreviewStaticItem1.Name = "printPreviewStaticItem1";
            this.printPreviewStaticItem1.RightIndent = 1;
            this.printPreviewStaticItem1.TextAlignment = StringAlignment.Near;
            this.printPreviewStaticItem1.Type = "PageOfPages";
            this.barStaticItem1.Id = 0x30;
            this.barStaticItem1.Name = "barStaticItem1";
            this.barStaticItem1.TextAlignment = StringAlignment.Near;
            this.progressBarEditItem1.ContextSpecifier = this.printRibbonController1;
            this.progressBarEditItem1.Edit = this.repositoryItemProgressBar1;
            this.progressBarEditItem1.EditHeight = 12;
            this.progressBarEditItem1.Id = 0x31;
            this.progressBarEditItem1.Name = "progressBarEditItem1";
            this.progressBarEditItem1.Visibility = BarItemVisibility.Never;
            this.progressBarEditItem1.Width = 150;
            this.repositoryItemProgressBar1.Name = "repositoryItemProgressBar1";
            this.printPreviewBarItem48.Caption = "Dừng";
            this.printPreviewBarItem48.Command = PrintingSystemCommand.StopPageBuilding;
            this.printPreviewBarItem48.ContextSpecifier = this.printRibbonController1;
            this.printPreviewBarItem48.Enabled = false;
            this.printPreviewBarItem48.Hint = "Stop";
            this.printPreviewBarItem48.Id = 50;
            this.printPreviewBarItem48.Name = "printPreviewBarItem48";
            this.printPreviewBarItem48.Visibility = BarItemVisibility.Never;
            this.barButtonItem1.Alignment = BarItemLinkAlignment.Left;
            this.barButtonItem1.Enabled = false;
            this.barButtonItem1.Id = 0x33;
            this.barButtonItem1.Name = "barButtonItem1";
            this.printPreviewStaticItem2.Alignment = BarItemLinkAlignment.Right;
            this.printPreviewStaticItem2.AutoSize = BarStaticItemSize.None;
            this.printPreviewStaticItem2.Caption = "100%";
            this.printPreviewStaticItem2.Id = 0x34;
            this.printPreviewStaticItem2.Name = "printPreviewStaticItem2";
            this.printPreviewStaticItem2.TextAlignment = StringAlignment.Near;
            this.printPreviewStaticItem2.Type = "ZoomFactorText";
            this.printPreviewStaticItem2.Width = 0x2a;
            this.zoomTrackBarEditItem1.Alignment = BarItemLinkAlignment.Right;
            this.zoomTrackBarEditItem1.ContextSpecifier = this.printRibbonController1;
            this.zoomTrackBarEditItem1.Edit = this.repositoryItemZoomTrackBar1;
            this.zoomTrackBarEditItem1.EditValue = 90;
            this.zoomTrackBarEditItem1.Enabled = false;
            this.zoomTrackBarEditItem1.Id = 0x35;
            this.zoomTrackBarEditItem1.Name = "zoomTrackBarEditItem1";
            this.zoomTrackBarEditItem1.Width = 140;
            this.repositoryItemZoomTrackBar1.AllowFocused = false;
            this.repositoryItemZoomTrackBar1.BorderStyle = BorderStyles.NoBorder;
            this.repositoryItemZoomTrackBar1.Maximum = 180;
            this.repositoryItemZoomTrackBar1.Name = "repositoryItemZoomTrackBar1";
            this.repositoryItemZoomTrackBar1.ScrollThumbStyle = ScrollThumbStyle.ArrowDownRight;
            this.bbiDesignView.Caption = "barButtonItem2";
            this.bbiDesignView.Hint = "Chỉnh Sửa";
            this.bbiDesignView.Id = 0x37;
            this.bbiDesignView.ImageIndex = 0;
            this.bbiDesignView.Name = "bbiDesignView";
            this.bbiDesignView.Visibility = BarItemVisibility.Never;
            this.bbiDesignView.ItemClick += new ItemClickEventHandler(this.bbiDesignView_ItemClick);
            this.rbgpPrintPreview.ContextSpecifier = this.printRibbonController1;
            this.rbgpPrintPreview.Groups.AddRange(new RibbonPageGroup[] { this.rbpDocument, this.rbpPrint, this.rbpPageSetup, this.rbpNavigation, this.rbpZoom, this.rbpPageBackground, this.rbpExport });
            this.rbgpPrintPreview.Name = "rbgpPrintPreview";
            this.rbgpPrintPreview.Text = "T\x00f9y Chọn";
            this.rbpDocument.ContextSpecifier = this.printRibbonController1;
            this.rbpDocument.Glyph = PrintRibbonControllerResources.RibbonPrintPreview_Document;
            this.rbpDocument.ItemLinks.Add(this.bbiOpen);
            this.rbpDocument.ItemLinks.Add(this.bbiSave);
            this.rbpDocument.Kind = PrintPreviewRibbonPageGroupKind.Document;
            this.rbpDocument.Name = "rbpDocument";
            this.rbpDocument.ShowCaptionButton = false;
            this.rbpDocument.Text = "T\x00e0i Liệu";
            this.rbpPrint.ContextSpecifier = this.printRibbonController1;
            this.rbpPrint.Glyph = PrintRibbonControllerResources.RibbonPrintPreview_PrintDirect;
            this.rbpPrint.ItemLinks.Add(this.bbiPrint);
            this.rbpPrint.ItemLinks.Add(this.bbiQuickPrint);
            this.rbpPrint.ItemLinks.Add(this.bbiOptions);
            this.rbpPrint.ItemLinks.Add(this.bbiParameters);
            this.rbpPrint.Kind = PrintPreviewRibbonPageGroupKind.Print;
            this.rbpPrint.Name = "rbpPrint";
            this.rbpPrint.ShowCaptionButton = false;
            this.rbpPrint.Text = "In";
            this.rbpPageSetup.ContextSpecifier = this.printRibbonController1;
            this.rbpPageSetup.Glyph = PrintRibbonControllerResources.RibbonPrintPreview_PageMargins;
            this.rbpPageSetup.ItemLinks.Add(this.bbiHeaderFooter);
            this.rbpPageSetup.ItemLinks.Add(this.bbiScale);
            this.rbpPageSetup.ItemLinks.Add(this.bbiMargins);
            this.rbpPageSetup.ItemLinks.Add(this.bbiOrientation);
            this.rbpPageSetup.ItemLinks.Add(this.bbiSize);
            this.rbpPageSetup.Kind = PrintPreviewRibbonPageGroupKind.PageSetup;
            this.rbpPageSetup.Name = "rbpPageSetup";
            tip48.FixedTooltipWidth = true;
            item95.Text = "Page Setup";
            item96.Appearance.Image = PrintRibbonControllerResources.RibbonPrintPreview_PageSetupDialog;
            item96.Appearance.Options.UseImage = true;
            item96.Image = PrintRibbonControllerResources.RibbonPrintPreview_PageSetupDialog;
            item96.LeftIndent = 6;
            item96.Text = "Show the Page Setup dialog.";
            tip48.Items.Add(item95);
            tip48.Items.Add(item96);
            tip48.MaxWidth = 0x13e;
            this.rbpPageSetup.SuperTip = tip48;
            this.rbpPageSetup.Text = "Cấu H\x00ecnh Trang In";
            this.rbpNavigation.ContextSpecifier = this.printRibbonController1;
            this.rbpNavigation.Glyph = PrintRibbonControllerResources.RibbonPrintPreview_Find;
            this.rbpNavigation.ItemLinks.Add(this.bbiFind);
            this.rbpNavigation.ItemLinks.Add(this.bbiBookmarks);
            this.rbpNavigation.ItemLinks.Add(this.bbiFirstPage, true);
            this.rbpNavigation.ItemLinks.Add(this.bbiPreviousPage);
            this.rbpNavigation.ItemLinks.Add(this.bbiNextPage);
            this.rbpNavigation.ItemLinks.Add(this.bbiLastPage);
            this.rbpNavigation.Kind = PrintPreviewRibbonPageGroupKind.Navigation;
            this.rbpNavigation.Name = "rbpNavigation";
            this.rbpNavigation.ShowCaptionButton = false;
            this.rbpNavigation.Text = "Điều Hướng";
            this.rbpZoom.ContextSpecifier = this.printRibbonController1;
            this.rbpZoom.Glyph = PrintRibbonControllerResources.RibbonPrintPreview_Zoom;
            this.rbpZoom.ItemLinks.Add(this.bbiPointer);
            this.rbpZoom.ItemLinks.Add(this.bbiHandTool);
            this.rbpZoom.ItemLinks.Add(this.bbiMagnifier);
            this.rbpZoom.ItemLinks.Add(this.bbiManyPages);
            this.rbpZoom.ItemLinks.Add(this.bbiZoomOut);
            this.rbpZoom.ItemLinks.Add(this.bbiZoom);
            this.rbpZoom.ItemLinks.Add(this.bbiZoomIn);
            this.rbpZoom.Kind = PrintPreviewRibbonPageGroupKind.Zoom;
            this.rbpZoom.Name = "rbpZoom";
            this.rbpZoom.ShowCaptionButton = false;
            this.rbpZoom.Text = "Ph\x00f3ng To/Thu Nhỏ";
            this.rbpPageBackground.ContextSpecifier = this.printRibbonController1;
            this.rbpPageBackground.Glyph = PrintRibbonControllerResources.RibbonPrintPreview_Watermark;
            this.rbpPageBackground.ItemLinks.Add(this.bbiPageColor);
            this.rbpPageBackground.ItemLinks.Add(this.bbiWatermark);
            this.rbpPageBackground.Kind = PrintPreviewRibbonPageGroupKind.Background;
            this.rbpPageBackground.Name = "rbpPageBackground";
            this.rbpPageBackground.ShowCaptionButton = false;
            this.rbpPageBackground.Text = "Trang Tr\x00ed";
            this.rbpExport.ContextSpecifier = this.printRibbonController1;
            this.rbpExport.Glyph = PrintRibbonControllerResources.RibbonPrintPreview_ExportFile;
            this.rbpExport.ItemLinks.Add(this.bbiExportTo);
            this.rbpExport.ItemLinks.Add(this.bbiEmailAs);
            this.rbpExport.ItemLinks.Add(this.bbiClosePrintPreview, true);
            this.rbpExport.Kind = PrintPreviewRibbonPageGroupKind.Export;
            this.rbpExport.Name = "rbpExport";
            this.rbpExport.ShowCaptionButton = false;
            this.rbpExport.Text = "Kết Xuất";
            this.ribbonStatusBar1.ItemLinks.Add(this.printPreviewStaticItem1);
            this.ribbonStatusBar1.ItemLinks.Add(this.barStaticItem1, true);
            this.ribbonStatusBar1.ItemLinks.Add(this.progressBarEditItem1);
            this.ribbonStatusBar1.ItemLinks.Add(this.printPreviewBarItem48);
            this.ribbonStatusBar1.ItemLinks.Add(this.barButtonItem1);
            this.ribbonStatusBar1.ItemLinks.Add(this.printPreviewStaticItem2);
            this.ribbonStatusBar1.ItemLinks.Add(this.zoomTrackBarEditItem1);
            this.ribbonStatusBar1.Location = new Point(0, 0x279);
            this.ribbonStatusBar1.Name = "ribbonStatusBar1";
            this.ribbonStatusBar1.Ribbon = this.ribbonControl1;
            this.ribbonStatusBar1.Size = new Size(0x426, 0x19);
            base.AutoScaleDimensions = new SizeF(6f, 13f);
            base.AutoScaleMode = AutoScaleMode.Font;
            base.ClientSize = new Size(0x426, 0x292);
            base.Controls.Add(this.printControl1);
            base.Controls.Add(this.ribbonStatusBar1);
            base.Controls.Add(this.ribbonControl1);
            base.Icon = (Icon) manager.GetObject("$this.Icon");
            base.Name = "xfmReport";
            this.Ribbon = this.ribbonControl1;
            base.StartPosition = FormStartPosition.CenterScreen;
            this.StatusBar = this.ribbonStatusBar1;
            this.Text = "B\x00e1o C\x00e1o - Perfect HRM 2012";
            base.WindowState = FormWindowState.Maximized;
            this.printRibbonController1.EndInit();
            this.ribbonControl1.EndInit();
            this.imageCollection1.EndInit();
            this.repositoryItemProgressBar1.EndInit();
            this.repositoryItemZoomTrackBar1.EndInit();
            base.ResumeLayout(false);
        }

        private void InitMultiLanguages()
        {
            //this.rbgpPrintPreview.Text = MultiLanguages.GetString("tbl_Report", "PrintPreview", this.rbgpPrintPreview.Text);
            //this.rbpDocument.Text = MultiLanguages.GetString("tbl_Report", "Document", this.rbpDocument.Text);
            //this.rbpPrint.Text = MultiLanguages.GetString("tbl_Report", "Print", this.rbpPrint.Text);
            //this.rbpPageSetup.Text = MultiLanguages.GetString("tbl_Report", "PageSetup", this.rbpPageSetup.Text);
            //this.rbpNavigation.Text = MultiLanguages.GetString("tbl_Report", "Navigation", this.rbpNavigation.Text);
            //this.rbpZoom.Text = MultiLanguages.GetString("tbl_Report", "Zoom", this.rbpZoom.Text);
            //this.rbpPageBackground.Text = MultiLanguages.GetString("tbl_Report", "PageBackground", this.rbpPageBackground.Text);
            //this.rbpExport.Text = MultiLanguages.GetString("tbl_Report", "Export", this.rbpExport.Text);
            //this.bbiOpen.Caption = MultiLanguages.GetString("tbl_Report", "Open", this.bbiOpen.Caption);
            //this.bbiSave.Caption = MultiLanguages.GetString("tbl_Report", "Save", this.bbiSave.Caption);
            //this.bbiPrint.Caption = MultiLanguages.GetString("tbl_Report", "Print", this.bbiPrint.Caption);
            //this.bbiQuickPrint.Caption = MultiLanguages.GetString("tbl_Report", "QuickPrint", this.bbiQuickPrint.Caption);
            //this.bbiOptions.Caption = MultiLanguages.GetString("tbl_Report", "Options", this.bbiOptions.Caption);
            //this.bbiParameters.Caption = MultiLanguages.GetString("tbl_Report", "Parameters", this.bbiParameters.Caption);
            //this.bbiHeaderFooter.Caption = MultiLanguages.GetString("tbl_Report", "HeaderFooter", this.bbiHeaderFooter.Caption);
            //this.bbiScale.Caption = MultiLanguages.GetString("tbl_Report", "Scale", this.bbiScale.Caption);
            //this.bbiMargins.Caption = MultiLanguages.GetString("tbl_Report", "Margins", this.bbiMargins.Caption);
            //this.bbiOrientation.Caption = MultiLanguages.GetString("tbl_Report", "Orientation", this.bbiOrientation.Caption);
            //this.bbiSize.Caption = MultiLanguages.GetString("tbl_Report", "Size", this.bbiSize.Caption);
            //this.bbiFind.Caption = MultiLanguages.GetString("tbl_Report", "Find", this.bbiFind.Caption);
            //this.bbiBookmarks.Caption = MultiLanguages.GetString("tbl_Report", "Bookmarks", this.bbiBookmarks.Caption);
            //this.bbiFirstPage.Caption = MultiLanguages.GetString("tbl_Report", "FirstPage", this.bbiFirstPage.Caption);
            //this.bbiPreviousPage.Caption = MultiLanguages.GetString("tbl_Report", "PreviousPage", this.bbiPreviousPage.Caption);
            //this.bbiNextPage.Caption = MultiLanguages.GetString("tbl_Report", "NextPage", this.bbiNextPage.Caption);
            //this.bbiLastPage.Caption = MultiLanguages.GetString("tbl_Report", "LastPage", this.bbiLastPage.Caption);
            //this.bbiManyPages.Caption = MultiLanguages.GetString("tbl_Report", "ManyPages", this.bbiManyPages.Caption);
            //this.bbiZoomOut.Caption = MultiLanguages.GetString("tbl_Report", "ZoomOut", this.bbiZoomOut.Caption);
            //this.bbiZoom.Caption = MultiLanguages.GetString("tbl_Report", "Zoom", this.bbiZoom.Caption);
            //this.bbiZoomIn.Caption = MultiLanguages.GetString("tbl_Report", "ZoomIn", this.bbiZoomIn.Caption);
            //this.bbiPageColor.Caption = MultiLanguages.GetString("tbl_Report", "PageColor", this.bbiPageColor.Caption);
            //this.bbiWatermark.Caption = MultiLanguages.GetString("tbl_Report", "Watermark", this.bbiWatermark.Caption);
            //this.bbiExportTo.Caption = MultiLanguages.GetString("tbl_Report", "ExportTo", this.bbiExportTo.Caption);
            //this.bbiEmailAs.Caption = MultiLanguages.GetString("tbl_Report", "EmailAs", this.bbiEmailAs.Caption);
            //this.bbiClosePrintPreview.Caption = MultiLanguages.GetString("tbl_Report", "ClosePrintPreview", this.bbiClosePrintPreview.Caption);
        }

        public void SetTitle(string Title)
        {
            this.Text = Title + " (B\x00e1o C\x00e1o - Perfect HRM 2012)";
        }

        public void ShowPrintPreview(ChartControl chartControl)
        {
            PrintingSystem system = new PrintingSystem();
            PrintableComponentLink link = new PrintableComponentLink {
                Component = chartControl
            };
            system.Links.AddRange(new object[] { link });
            this.printControl1.PrintingSystem = link.PrintingSystem;
            link.CreateDocument();
            base.Show();
        }

        public void ShowPrintPreview(GridControl gridControl)
        {
            PrintingSystem system = new PrintingSystem();
            PrintableComponentLink link = new PrintableComponentLink {
                Component = gridControl
            };
            system.Links.AddRange(new object[] { link });
            this.printControl1.PrintingSystem = link.PrintingSystem;
            link.CreateDocument();
            base.Show();
        }

        public void ShowPrintPreview(XtraReport xtraReport)
        {
            this.m_xtraReport = xtraReport;
            this.printControl1.PrintingSystem = xtraReport.PrintingSystem;
            xtraReport.CreateDocument();
            base.Show();
        }

        public void ShowPrintPreview(TreeList treeList)
        {
            PrintingSystem system = new PrintingSystem();
            PrintableComponentLink link = new PrintableComponentLink {
                Component = treeList
            };
            system.Links.AddRange(new object[] { link });
            this.printControl1.PrintingSystem = link.PrintingSystem;
            link.CreateDocument();
            base.Show();
        }
    }
}

